import { supabase } from '../lib/supabaseClient';
import type { AuditAgenda,AuditAgendaItem,AuditInstruction,AuditInstructionRow,AuditTeamMaster,ChecklistManufakturShift,ChecklistProduk,Finding,InternalAuditReport,InternalAuditReportAttendee,InternalAuditReportContext,InternalAuditReportFindingCounts,InternalAuditReportFindingSummaryGroup,InternalAuditReportFollowUpItem,InternalAuditReportWorklistRow,Proses,SaveInternalAuditReportDraftPayload,Seksi,SeksiMark } from '../lib/types';
import { KODE_DOKUMEN_LAPORAN_INTERNAL_AUDIT } from '../lib/enums';

const ESTABLISHED=new Set(['PUBLISHED','LEGACY_ESTABLISHED']);
const ACTIVE=(finding:Finding)=>finding.review_status!=='ANNULLED';
function report(row:Record<string,unknown>):InternalAuditReport{return{...row,auditee_hadir:(row.auditee_hadir??[]) as InternalAuditReportAttendee[],follow_up_items:(row.follow_up_items??[]) as InternalAuditReportFollowUpItem[],kode_dokumen:(row.kode_dokumen as string)||KODE_DOKUMEN_LAPORAN_INTERNAL_AUDIT} as InternalAuditReport;}
function eligibilityReason(hasAgenda:boolean,hasChecklist:boolean,hasSections=true):string|null {if(!hasSections)return 'Seksi lingkup audit belum ditentukan.';if(hasAgenda&&hasChecklist)return null;if(!hasAgenda&&!hasChecklist)return 'Agenda dan Checklist belum tersedia.';return hasAgenda?'Checklist belum tersedia.':'Agenda belum dibuat.';}
function scopeIds(marks:SeksiMark[]):string[]{return [...new Set((marks??[]).filter(mark=>mark.tipe==='target'||mark.tipe==='terkait').map(mark=>mark.seksi_id).filter(Boolean))];}
function formatAuditTimeRange(items:AuditAgendaItem[]):string{if(!items.length)return '-';const sorted=[...items].sort((a,b)=>`${a.tanggal}T${a.jam_mulai}`.localeCompare(`${b.tanggal}T${b.jam_mulai}`));const ended=[...items].sort((a,b)=>`${a.tanggal}T${a.jam_selesai}`.localeCompare(`${b.tanggal}T${b.jam_selesai}`));const first=sorted[0],last=ended[ended.length-1];const date=(v:string)=>new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(`${v}T00:00:00Z`));const time=(v:string)=>v.slice(0,5).replace('.',':');return first.tanggal===last.tanggal?`${date(first.tanggal)}, ${time(first.jam_mulai)}–${time(last.jam_selesai)}`:`${date(first.tanggal)} ${time(first.jam_mulai)} – ${date(last.tanggal)} ${time(last.jam_selesai)}`;}
export function uniqueFindingReferences(findings:Pick<Finding,'reference'>[]):string[]{return[...new Set(findings.map(v=>v.reference?.trim()).filter((v):v is string=>!!v))].sort((a,b)=>a.localeCompare(b,'id-ID',{numeric:true}));}
export function groupInternalAuditReportFindings(findings:Finding[]):InternalAuditReportFindingSummaryGroup[]{const groups=new Map<string,InternalAuditReportFindingSummaryGroup>();for(const finding of [...findings].sort((a,b)=>a.nomor_urut_temuan-b.nomor_urut_temuan||a.id.localeCompare(b.id))){const reference=finding.reference?.trim()||null,location=finding.location?.trim()||null,key=JSON.stringify([reference,location]),requirement=finding.problem?.trim()||null;const current=groups.get(key)??{reference,location,finding_numbers:[],requirement,requirements:[],counts:{A:0,B:0,C:0}};current.finding_numbers.push(finding.nomor_urut_temuan);if(requirement&&!current.requirements.includes(requirement))current.requirements.push(requirement);current.requirement=current.requirements.join('\n');current.counts[finding.kategori]+=1;groups.set(key,current);}return[...groups.values()];}
export function meaningfulOptionalValue(value?:string|null):string|null{const normalized=value?.trim()??'';return normalized&&normalized!=='-'&&normalized!=='—'?normalized:null;}
export function generateHasilPengamatanDraft(input:{proses:string|null;seksi:string;counts:InternalAuditReportFindingCounts;nama_customer?:string|null;nama_produk?:string|null;}):string{const process=input.proses?.trim()||'yang ditetapkan',section=input.seksi.trim();const product=meaningfulOptionalValue(input.nama_produk),customer=meaningfulOptionalValue(input.nama_customer);const context=product&&customer?` untuk produk ${product} milik customer ${customer}`:product?` untuk produk ${product}`:customer?` untuk customer ${customer}`:'';const opening=`Telah dilakukan Internal Audit pada proses ${process}${context} pada Seksi ${section}.`;if(input.counts.A+input.counts.B+input.counts.C===0)return `${opening} Berdasarkan hasil verifikasi, pelaksanaan proses ${process} pada Seksi ${section} telah sesuai dengan ketentuan yang berlaku.`;return `${opening} Berdasarkan hasil audit, ditemukan ${input.counts.A} ketidaksesuaian Major, ${input.counts.B} ketidaksesuaian Minor, dan ${input.counts.C} Peluang Improvement.`;}
export function generateEvaluasiDraft(input:{seksi:string;counts:InternalAuditReportFindingCounts;references:string[]}):string{if(input.counts.A+input.counts.B+input.counts.C===0)return `Pelaksanaan pada Seksi ${input.seksi} telah memenuhi persyaratan yang diperiksa. Pertahankan penerapan dan pemantauan yang sudah berjalan.`;if(!input.references.length)return `Temuan pada Seksi ${input.seksi} perlu ditindaklanjuti sesuai hasil audit.`;return `Temuan pada Seksi ${input.seksi} terkait dengan persyaratan: ${input.references.join(', ')}. Mohon dilakukan tindak lanjut sesuai hasil audit.`;}
function friendlyError(message:string):Error{if(message.includes('duplicate key')||message.includes('scoped_unique'))return new Error('Laporan Internal Audit untuk No. Audit dan Seksi ini sudah ada.');return new Error(message);}

async function loadWorklist():Promise<InternalAuditReportWorklistRow[]>{const results=await Promise.all([supabase.from('audit_instruction_rows').select('*').order('kode_audit'),supabase.from('audit_instructions').select('*'),supabase.from('proses').select('*'),supabase.from('seksi').select('*'),supabase.from('audit_team_masters').select('*,members:audit_team_master_members(*,auditor:auditors(*))'),supabase.from('audit_agendas').select('*'),supabase.from('audit_agenda_items').select('*').order('tanggal').order('jam_mulai').order('urutan'),supabase.from('checklists').select('id,row_id'),supabase.from('checklist_produk').select('id,row_id,part_name'),supabase.from('checklist_manufaktur_shift').select('id,row_id,customer,nama_part,nomor_line'),supabase.from('findings').select('*').order('nomor_urut_temuan'),supabase.from('audit_internal_reports').select('*')]);const failure=results.find(v=>v.error);if(failure?.error)throw new Error(`Gagal memuat workspace Laporan Internal Audit: ${failure.error.message}`);const [rr,ir,pr,sr,tr,ar,air,sysr,prodr,mfr,fr,repr]=results;const instructions=(ir.data??[]) as AuditInstruction[],processes=(pr.data??[]) as Proses[],sections=(sr.data??[]) as Seksi[],teams=(tr.data??[]) as unknown as AuditTeamMaster[],agendas=(ar.data??[]) as AuditAgenda[],items=(air.data??[]) as AuditAgendaItem[],products=(prodr.data??[]) as Pick<ChecklistProduk,'id'|'row_id'|'part_name'>[],manufacturing=(mfr.data??[]) as Pick<ChecklistManufakturShift,'id'|'row_id'|'customer'|'nama_part'|'nomor_line'>[],findings=(fr.data??[]) as Finding[],reports=(repr.data??[]).map(v=>report(v as Record<string,unknown>)),systems=(sysr.data??[]) as {id:string;row_id:string}[];
return((rr.data??[]) as AuditInstructionRow[]).flatMap(row=>{const instruction=instructions.find(v=>v.id===row.instruction_id);if(!instruction)return[];const agenda=agendas.find(v=>v.instruction_row_id===row.id)??null,agenda_items=items.filter(v=>v.agenda_id===agenda?.id),checklist_presence={sistem:systems.some(v=>v.row_id===row.id),produk:products.some(v=>v.row_id===row.id),manufaktur_shift:manufacturing.some(v=>v.row_id===row.id)},ids=scopeIds(row.seksi_marks),scope=ids.map(id=>sections.find(v=>v.id===id)).filter((v):v is Seksi=>!!v),rowFindings=findings.filter(v=>v.instruction_row_id===row.id),team=teams.find(v=>v.id===row.team_master_id)??null,leader=team?.members.find(v=>v.is_team_leader)?.auditor??null,members=team?.members.filter(v=>!v.is_team_leader&&v.peran==='Member').map(v=>v.auditor).filter((v):v is NonNullable<typeof v>=>!!v)??[],unassigned=rowFindings.filter(v=>ACTIVE(v)&&!v.seksi_auditee_id).length,hasChecklist=Object.values(checklist_presence).some(Boolean);const contexts=scope.map(scope_section=>{const scoped=rowFindings.filter(v=>v.seksi_auditee_id===scope_section.id),established=scoped.filter(v=>ESTABLISHED.has(v.review_status)),pending=scoped.filter(v=>ACTIVE(v)&&!ESTABLISHED.has(v.review_status)),counts=established.reduce<InternalAuditReportFindingCounts>((a,v)=>({...a,[v.kategori]:a[v.kategori]+1}),{A:0,B:0,C:0}),reportValue=reports.find(v=>v.instruction_row_id===row.id&&v.seksi_id===scope_section.id)??null;return{row,instruction,proses:processes.find(v=>v.id===row.proses_id)??null,sections:scope,scope_section,agenda,agenda_items,team,team_leader:leader,team_members:members,selected_sub_leader:members.find(v=>v.id===reportValue?.sub_leader_auditor_id)??null,remaining_members:members.filter(v=>v.id!==reportValue?.sub_leader_auditor_id),checklist_presence,findings:scoped,established_findings:established,pending_findings:pending,unassigned_finding_count:unassigned,finding_counts:counts,finding_references:uniqueFindingReferences(established),finding_summary_groups:groupInternalAuditReportFindings(established),report:reportValue,eligible:!!agenda&&hasChecklist,eligibility_reason:eligibilityReason(!!agenda,hasChecklist),audit_time_range:formatAuditTimeRange(agenda_items)} satisfies InternalAuditReportContext;});return[{row,instruction,proses:processes.find(v=>v.id===row.proses_id)??null,agenda,checklist_presence,scope_sections:contexts,legacy_report:reports.find(v=>v.instruction_row_id===row.id&&!v.seksi_id)??null,established_finding_count:rowFindings.filter(v=>ESTABLISHED.has(v.review_status)).length,pending_finding_count:rowFindings.filter(v=>ACTIVE(v)&&!ESTABLISHED.has(v.review_status)&&!!v.seksi_auditee_id).length,unassigned_finding_count:unassigned,eligible:!!agenda&&hasChecklist&&scope.length>0,eligibility_reason:eligibilityReason(!!agenda,hasChecklist,scope.length>0)}];});}
export async function listInternalAuditReportWorklist(){return loadWorklist();}
export async function getInternalAuditReportContext(instructionRowId:string,seksiId:string){const row=(await loadWorklist()).find(v=>v.row.id===instructionRowId),context=row?.scope_sections.find(v=>v.scope_section.id===seksiId);if(!context)throw new Error('Seksi laporan tidak ditemukan dalam lingkup audit.');return context;}
export async function createInternalAuditReport(instructionRowId:string,seksiId:string){const{data,error}=await supabase.rpc('create_internal_audit_report_for_section',{p_instruction_row_id:instructionRowId,p_seksi_id:seksiId});if(error)throw friendlyError(error.message);return report(data as Record<string,unknown>);}
export async function assignInternalAuditReportSection(reportId:string,expectedRevision:number,seksiId:string){const{data,error}=await supabase.rpc('assign_internal_audit_report_section',{p_report_id:reportId,p_expected_revision:expectedRevision,p_seksi_id:seksiId});if(error)throw friendlyError(error.message);return report(data as Record<string,unknown>);}
export async function saveInternalAuditReportDraft(payload:SaveInternalAuditReportDraftPayload){const{data,error}=await supabase.rpc('save_internal_audit_report_draft',{p_report_id:payload.report_id,p_expected_revision:payload.expected_revision,p_tanggal_terbit:payload.tanggal_terbit,p_auditee_hadir:payload.auditee_hadir,p_nama_customer:payload.nama_customer,p_nama_produk:payload.nama_produk,p_nama_line:payload.nama_line,p_sub_leader_auditor_id:payload.sub_leader_auditor_id,p_leader_signatory_auditor_id:payload.leader_signatory_auditor_id,p_hasil_pengamatan:payload.hasil_pengamatan,p_evaluasi:payload.evaluasi,p_follow_up_required:payload.follow_up_required,p_follow_up_items:payload.follow_up_items,p_catatan:payload.catatan});if(error)throw friendlyError(error.message);return report(data as Record<string,unknown>);}
export async function finalizeInternalAuditReport(reportId:string,expectedRevision:number){const{data,error}=await supabase.rpc('finalize_internal_audit_report',{p_report_id:reportId,p_expected_revision:expectedRevision});if(error)throw friendlyError(error.message);return report(data as Record<string,unknown>);}
