import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowUp, Plus, Trash2 } from 'lucide-react';
import type { AgendaAssistantAuditor, AgendaWorklistRow, AuditAgenda, AuditAgendaItem } from '../../lib/types';
import { KODE_DOKUMEN_AGENDA_INTERNAL_AUDIT } from '../../lib/enums';
import { createAgendaFromRow, deleteAgendaItem, finalizeAgenda, listAgendaItems, listAgendaWorklist, reorderAgendaItems, returnAgendaToDraft, saveAgendaItem, saveDraftAgenda } from '../../services/auditAgendaService';
import { formatTanggal, toDateInput } from '../../lib/utils';
import { Badge, Button, Card, EmptyState, LoadingSpinner } from '../ui';
import { Input, Textarea } from '../ui/Field';

const badge = { 'Belum Dibuat': 'gray', Draft: 'blue', Final: 'green' } as const;
function blankItem(agendaId:string,date:string,order:number):Partial<AuditAgendaItem>{return{agenda_id:agendaId,tanggal:date||toDateInput(new Date()),jam_mulai:'08:00',jam_selesai:'09:00',detail_audit_proses_persyaratan:'',lokasi:null,urutan:order};}

export function AgendaAuditPage({ initialRowId, onClearInitial }:{initialRowId:string|null;onClearInitial:()=>void}) {
  const [rows,setRows]=useState<AgendaWorklistRow[]>([]);const [selected,setSelected]=useState<AgendaWorklistRow|null>(null);
  const [items,setItems]=useState<AuditAgendaItem[]>([]);const [newItem,setNewItem]=useState<Partial<AuditAgendaItem>|null>(null);
  const [search,setSearch]=useState('');const [status,setStatus]=useState('Semua');const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const data=await listAgendaWorklist();setRows(data);if(selected)setSelected(data.find((r)=>r.row.id===selected.row.id)??null);}catch(e){setError(e instanceof Error?e.message:'Gagal memuat Agenda');}finally{setLoading(false);}},[selected]);
  useEffect(()=>{void (async()=>{setLoading(true);try{const data=await listAgendaWorklist();setRows(data);if(initialRowId){setSelected(data.find((r)=>r.row.id===initialRowId)??null);onClearInitial();}}catch(e){setError(e instanceof Error?e.message:'Gagal memuat Agenda');}finally{setLoading(false);}})();},[initialRowId,onClearInitial]);
  useEffect(()=>{if(selected?.agenda)void listAgendaItems(selected.agenda.id).then(setItems).catch((e)=>setError(e.message));else setItems([]);},[selected]);
  const filtered=useMemo(()=>rows.filter((r)=>(status==='Semua'||r.status_agenda===status)&&`${r.row.kode_audit} ${r.proses?.nama_proses??''}`.toLowerCase().includes(search.toLowerCase())),[rows,search,status]);
  async function act(task:()=>Promise<unknown>){setBusy(true);setError(null);try{await task();await load();}catch(e){setError(e instanceof Error?e.message:'Operasi Agenda gagal');}finally{setBusy(false);}}
  async function open(row:AgendaWorklistRow){if(!row.agenda){await act(async()=>{await createAgendaFromRow(row.row.id);});const refreshed=await listAgendaWorklist();setRows(refreshed);setSelected(refreshed.find((r)=>r.row.id===row.row.id)??null);}else setSelected(row);}
  if(loading)return <LoadingSpinner/>;
  if(selected)return <AgendaDetail context={selected} items={items} setItems={setItems} newItem={newItem} setNewItem={setNewItem} busy={busy} error={error} onBack={()=>{setSelected(null);setError(null);}} onAct={act}/>;
  return <div><div className="mb-6"><h1 className="text-2xl font-bold text-gray-900">Agenda Internal Audit</h1><p className="text-sm text-gray-500 mt-1">Workspace agenda per No. Audit QA dari Instruksi Internal Audit.</p></div>
    {error&&<div className="mb-4 p-3 bg-red-50 border border-red-200 rounded text-sm text-red-700">{error}</div>}
    <Card className="p-4 mb-4 flex gap-3"><Input value={search} onChange={(e)=>setSearch(e.target.value)} placeholder="Cari No. Audit atau proses..."/><select className="border rounded-lg px-3 text-sm" value={status} onChange={(e)=>setStatus(e.target.value)}><option>Semua</option><option>Belum Dibuat</option><option>Draft</option><option>Final</option></select></Card>
    {filtered.length===0?<Card className="p-10"><EmptyState title="Agenda tidak ditemukan" message="Belum ada baris Instruksi yang sesuai filter."/></Card>:<Card className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50 border-b">{['No. Audit','Proses yang Diaudit','Seksi','Manager','Team Audit','Tanggal Pelaksanaan','Status Agenda','Aksi'].map((h)=><th key={h} className="p-3 text-left text-xs uppercase text-gray-500">{h}</th>)}</tr></thead><tbody>{filtered.map((r)=><tr key={r.row.id} className="border-b"><td className="p-3 font-semibold text-blue-800">{r.row.kode_audit}</td><td className="p-3">{r.proses?.nama_proses??'-'}</td><td className="p-3">{r.seksi.map((s)=>s.nama).join(', ')||'-'}</td><td className="p-3">{r.managers.join(', ')||'-'}</td><td className="p-3">{r.team?`${r.team.kode_tim} — ${r.team.nama_tim}`:'-'}</td><td className="p-3 whitespace-nowrap">{r.row.tanggal_pelaksanaan_audit?formatTanggal(r.row.tanggal_pelaksanaan_audit):'-'}</td><td className="p-3"><Badge variant={badge[r.status_agenda]}>{r.status_agenda}</Badge></td><td className="p-3"><Button size="sm" disabled={busy} onClick={()=>void open(r)}>{!r.agenda?'Buat Agenda':r.agenda.status==='Final'?'Lihat Agenda':'Buka Agenda'}</Button></td></tr>)}</tbody></table></Card>}
  </div>;
}

function AgendaDetail({context,items,setItems,newItem,setNewItem,busy,error,onBack,onAct}:{context:AgendaWorklistRow;items:AuditAgendaItem[];setItems:(v:AuditAgendaItem[])=>void;newItem:Partial<AuditAgendaItem>|null;setNewItem:(v:Partial<AuditAgendaItem>|null)=>void;busy:boolean;error:string|null;onBack:()=>void;onAct:(task:()=>Promise<unknown>)=>Promise<void>}){
  const [form,setForm]=useState<AuditAgenda>(context.agenda!);useEffect(()=>setForm(context.agenda!),[context.agenda]);const readOnly=form.status==='Final';
  const update=(key:keyof AuditAgenda,value:unknown)=>setForm((old)=>({...old,[key]:value}));
  async function reloadItems(){setItems(await listAgendaItems(form.id));}
  async function saveItem(value:Partial<AuditAgendaItem>){await onAct(async()=>{await saveAgendaItem(value);await reloadItems();setNewItem(null);});}
  async function move(index:number,delta:number){const copy=[...items];const target=index+delta;if(target<0||target>=copy.length)return;[copy[index],copy[target]]=[copy[target],copy[index]];await onAct(async()=>{await reorderAgendaItems(form.id,copy.map((i)=>i.id));setItems(await listAgendaItems(form.id));});}
  const effective=new Map<string,string>();let last='';items.forEach((i)=>{if(i.lokasi?.trim())last=i.lokasi.trim();effective.set(i.id,last);});
  return <div className="max-w-6xl mx-auto"><button onClick={onBack} className="mb-4 text-sm text-blue-700 flex gap-1"><ArrowLeft size={16}/> Kembali ke Worklist</button>
    {error&&<div className="mb-4 p-3 bg-red-50 border border-red-200 rounded text-sm text-red-700">{error}</div>}
    <Card className="p-6 print:shadow-none"><div className="flex justify-between border-b pb-4 mb-5"><div><p className="text-xs font-semibold text-blue-700">DOKUMEN AUDIT</p><h1 className="text-2xl font-bold">AGENDA INTERNAL AUDIT</h1></div><div className="text-right"><Badge variant={form.status==='Final'?'green':'blue'}>{form.status}</Badge><p className="text-xs text-gray-500 mt-2">{KODE_DOKUMEN_AGENDA_INTERNAL_AUDIT}</p></div></div>
      <section className="mb-6"><SectionTitle title="Informasi Audit" auto/><div className="grid md:grid-cols-3 gap-3"><Read label="No. Audit" value={context.row.kode_audit}/><Read label="Proses yang Diaudit" value={context.proses?.nama_proses}/><Read label="Tipe Audit" value={context.row.tipe_baris}/><Read label="Seksi yang Diaudit" value={context.seksi.map((s)=>s.nama).join(', ')}/><Read label="Manager Seksi/Proses" value={context.managers.join(', ')}/><Read label="Tanggal Pelaksanaan" value={context.row.tanggal_pelaksanaan_audit?formatTanggal(context.row.tanggal_pelaksanaan_audit):undefined}/></div></section>
      <section className="mb-6"><SectionTitle title="Data Agenda"/><div className="grid md:grid-cols-2 gap-4"><label className="text-sm font-medium">Tanggal Terbit<Input type="date" disabled={readOnly} value={form.tanggal_terbit} onChange={(e)=>update('tanggal_terbit',e.target.value)}/></label><label className="text-sm font-medium md:col-span-2">Tujuan dan Lingkup Audit<Textarea disabled={readOnly} value={form.tujuan_lingkup_audit??''} onChange={(e)=>update('tujuan_lingkup_audit',e.target.value)}/></label></div></section>
      <section className="mb-6"><SectionTitle title="Audit Team" auto/><div className="grid md:grid-cols-3 gap-3"><Read label="Team Audit" value={context.team?`${context.team.kode_tim} — ${context.team.nama_tim}`:undefined}/><Read label="Lead Auditor" value={context.lead?.nama}/><Read label="Member Auditor" value={context.members.map((a)=>a.nama).join(', ')}/></div><AssistantEditor value={form.asisten_auditor_pendamping} disabled={readOnly} onChange={(v)=>update('asisten_auditor_pendamping',v)}/><label className="block text-sm font-medium mt-4">Item Lain yang Dicek<Textarea disabled={readOnly} value={form.item_lain_yang_dicek??''} onChange={(e)=>update('item_lain_yang_dicek',e.target.value)}/></label></section>
      <section className="mb-6"><SectionTitle title="Dokumen"/><div className="grid md:grid-cols-2 gap-4"><label className="text-sm font-medium">Dokumen yang Dikirim di Awal<Textarea disabled={readOnly} value={form.dokumen_dikirim_di_awal??''} onChange={(e)=>update('dokumen_dikirim_di_awal',e.target.value)}/></label><label className="text-sm font-medium">Dokumen yang Dipersiapkan di Hari Audit<Textarea disabled={readOnly} value={form.dokumen_dipersiapkan_hari_audit??''} onChange={(e)=>update('dokumen_dipersiapkan_hari_audit',e.target.value)}/></label></div></section>
      <section className="mb-6"><div className="flex justify-between"><SectionTitle title="Timeline Audit"/>{!readOnly&&!newItem&&<Button size="sm" onClick={()=>setNewItem(blankItem(form.id,context.row.tanggal_pelaksanaan_audit??'',items.length+1))}><Plus size={14}/> Tambah Kegiatan</Button>}</div><div className="space-y-2">{items.map((i,index)=><TimelineRow key={i.id} value={i} effective={effective.get(i.id)||''} disabled={readOnly} onSave={saveItem} onDelete={()=>onAct(async()=>{await deleteAgendaItem(i.id);await reloadItems();})} onUp={()=>move(index,-1)} onDown={()=>move(index,1)}/>)}{newItem&&<TimelineRow value={newItem} effective="" disabled={false} onSave={saveItem} onDelete={()=>setNewItem(null)} onUp={()=>{}} onDown={()=>{}}/>}</div></section>
      <section><SectionTitle title="Catatan Khusus"/><Textarea disabled={readOnly} value={form.catatan_khusus??''} onChange={(e)=>update('catatan_khusus',e.target.value)}/></section>
      <div className="flex justify-end gap-2 mt-6 pt-4 border-t">{!readOnly&&<><Button variant="secondary" disabled={busy} onClick={()=>onAct(async()=>setForm(await saveDraftAgenda(form)))}>Simpan</Button><Button disabled={busy} onClick={()=>onAct(async()=>{const saved=await saveDraftAgenda(form);setForm(await finalizeAgenda(saved.id));})}>Finalkan Agenda</Button></>}{readOnly&&<Button disabled={busy} onClick={()=>onAct(async()=>setForm(await returnAgendaToDraft(form.id)))}>Kembalikan ke Draft</Button>}</div>
    </Card></div>;
}
function SectionTitle({title,auto=false}:{title:string;auto?:boolean}){return <div className="flex gap-2 items-center mb-3 border-b pb-2"><h2 className="font-semibold text-gray-800">{title}</h2>{auto&&<span className="text-[10px] bg-blue-50 text-blue-700 px-2 py-0.5 rounded">AUTO / READ-ONLY</span>}</div>}
function Read({label,value}:{label:string;value?:string|null}){return <div className="bg-gray-50 border rounded p-3"><p className="text-xs text-gray-500">{label}</p><p className="text-sm font-medium mt-1">{value||'-'}</p></div>}
function AssistantEditor({value,disabled,onChange}:{value:AgendaAssistantAuditor[];disabled:boolean;onChange:(v:AgendaAssistantAuditor[])=>void}){return <div className="mt-4"><div className="flex justify-between"><p className="text-sm font-medium">Asisten Auditor Pendamping / Seksi (opsional)</p>{!disabled&&<button className="text-xs text-blue-700" onClick={()=>onChange([...value,{nama:'',seksi:''}])}>+ Tambah Asisten</button>}</div>{value.map((a,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-2 mt-2"><Input disabled={disabled} placeholder="Nama" value={a.nama} onChange={(e)=>onChange(value.map((x,j)=>j===i?{...x,nama:e.target.value}:x))}/><Input disabled={disabled} placeholder="Seksi" value={a.seksi} onChange={(e)=>onChange(value.map((x,j)=>j===i?{...x,seksi:e.target.value}:x))}/>{!disabled&&<button onClick={()=>onChange(value.filter((_,j)=>j!==i))}><Trash2 size={15}/></button>}</div>)}</div>}
function TimelineRow({value,effective,disabled,onSave,onDelete,onUp,onDown}:{value:Partial<AuditAgendaItem>;effective:string;disabled:boolean;onSave:(v:Partial<AuditAgendaItem>)=>void;onDelete:()=>void;onUp:()=>void;onDown:()=>void}){const [draft,setDraft]=useState(value);useEffect(()=>setDraft(value),[value]);return <div className="grid lg:grid-cols-[130px_100px_100px_1fr_180px_auto] gap-2 border rounded p-2 items-end"><Input type="date" disabled={disabled} value={draft.tanggal??''} onChange={(e)=>setDraft({...draft,tanggal:e.target.value})}/><Input type="time" disabled={disabled} value={draft.jam_mulai??''} onChange={(e)=>setDraft({...draft,jam_mulai:e.target.value})}/><Input type="time" disabled={disabled} value={draft.jam_selesai??''} onChange={(e)=>setDraft({...draft,jam_selesai:e.target.value})}/><Input disabled={disabled} placeholder="Detail Audit (Proses/Persyaratan)" value={draft.detail_audit_proses_persyaratan??''} onChange={(e)=>setDraft({...draft,detail_audit_proses_persyaratan:e.target.value})}/><div><Input disabled={disabled} placeholder="Mengikuti lokasi baris sebelumnya" value={draft.lokasi??''} onChange={(e)=>setDraft({...draft,lokasi:e.target.value})}/>{!draft.lokasi&&effective&&<p className="text-[10px] text-gray-500 mt-1">Efektif: {effective}</p>}</div>{!disabled&&<div className="flex gap-1"><button title="Naik" onClick={onUp}><ArrowUp size={14}/></button><button title="Turun" onClick={onDown}><ArrowDown size={14}/></button><button className="text-blue-700 text-xs" onClick={()=>onSave(draft)}>Simpan</button><button className="text-red-600" onClick={onDelete}><Trash2 size={14}/></button></div>}</div>}
