import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowUp, Plus, Trash2 } from 'lucide-react';
import type { AgendaAssistantAuditor, AgendaWorklistRow, AuditAgenda, AuditAgendaItem } from '../../lib/types';
import { KODE_DOKUMEN_AGENDA_INTERNAL_AUDIT } from '../../lib/enums';
import { createAgendaFromRow, finalizeAgenda, listAgendaItems, listAgendaWorklist, returnAgendaToDraft, saveAgendaDraftBundle } from '../../services/auditAgendaService';
import { formatTanggal, toDateInput } from '../../lib/utils';
import { Badge, Button, Card, EmptyState, LoadingSpinner } from '../ui';
import { Input, Textarea } from '../ui/Field';

interface TimelineDraftItem {
  client_id: string;
  tanggal: string;
  jam_mulai: string;
  jam_selesai: string;
  detail_audit_proses_persyaratan: string;
  lokasi: string | null;
}
const badge = { 'Belum Dibuat': 'gray', Draft: 'blue', Final: 'green' } as const;
const clientId = () => crypto.randomUUID();
const toDraftItem = (value: AuditAgendaItem): TimelineDraftItem => ({ client_id:value.id,tanggal:value.tanggal,jam_mulai:value.jam_mulai.slice(0,5),jam_selesai:value.jam_selesai.slice(0,5),detail_audit_proses_persyaratan:value.detail_audit_proses_persyaratan,lokasi:value.lokasi });

export function AgendaAuditPage({readOnly=false}:{readOnly?:boolean}) {
  const [rows,setRows]=useState<AgendaWorklistRow[]>([]); const [selected,setSelected]=useState<AgendaWorklistRow|null>(null); const [initialItems,setInitialItems]=useState<AuditAgendaItem[]>([]);
  const [search,setSearch]=useState(''); const [status,setStatus]=useState('Semua'); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{setRows(await listAgendaWorklist());}catch(e){setError(e instanceof Error?e.message:'Gagal memuat Agenda');}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  const filtered=useMemo(()=>rows.filter(r=>(status==='Semua'||r.status_agenda===status)&&`${r.row.kode_audit} ${r.proses?.nama_proses??''}`.toLowerCase().includes(search.toLowerCase())),[rows,search,status]);
  async function open(row:AgendaWorklistRow){setBusy(true);setError(null);try{if(readOnly&&!row.agenda)throw new Error('Agenda belum disiapkan oleh Admin.');const agenda=row.agenda??await createAgendaFromRow(row.row.id);const items=await listAgendaItems(agenda.id);setInitialItems(items);setSelected({...row,agenda,status_agenda:agenda.status});setRows(old=>old.map(value=>value.row.id===row.row.id?{...value,agenda,status_agenda:agenda.status}:value));}catch(e){setSelected(null);setError(e instanceof Error?e.message:'Agenda gagal dibuka. Silakan coba kembali dari worklist.');}finally{setBusy(false);}}
  if(loading)return <LoadingSpinner/>;
  if(selected?.agenda)return <AgendaDetail key={selected.agenda.id} context={selected} initialItems={initialItems} forceReadOnly={readOnly} onBack={()=>setSelected(null)} onAgendaChange={(agenda)=>{setSelected(old=>old?{...old,agenda,status_agenda:agenda.status}:old);setRows(old=>old.map(r=>r.row.id===selected.row.id?{...r,agenda,status_agenda:agenda.status}:r));}}/>;
  return <div><div className="mb-6"><h1 className="text-2xl font-bold text-gray-900">Agenda Internal Audit</h1><p className="text-sm text-gray-500 mt-1">Workspace pusat Agenda berbasis No. Audit QA.</p></div>
    {error&&<div className="mb-4 p-3 bg-red-50 border border-red-200 rounded text-sm text-red-700">{error}</div>}
    <Card className="p-4 mb-4 flex gap-3"><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari No. Audit atau proses..."/><select className="border rounded-lg px-3 text-sm" value={status} onChange={e=>setStatus(e.target.value)}><option>Semua</option><option>Belum Dibuat</option><option>Draft</option><option>Final</option></select></Card>
    {!filtered.length?<Card className="p-10"><EmptyState title="Agenda tidak ditemukan" message="Belum ada baris Instruksi yang sesuai filter."/></Card>:<Card className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50 border-b">{['No. Audit','Proses yang Diaudit','Seksi','Manager','Team Audit','Tanggal Pelaksanaan','Status Agenda','Aksi'].map(h=><th key={h} className="p-3 text-left text-xs uppercase text-gray-500">{h}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.row.id} className="border-b"><td className="p-3 font-semibold text-blue-800">{r.row.kode_audit}</td><td className="p-3">{r.proses?.nama_proses??'-'}</td><td className="p-3">{r.seksi.map(s=>s.nama).join(', ')||'-'}</td><td className="p-3">{r.managers.join(', ')||'-'}</td><td className="p-3">{r.team?`${r.team.kode_tim} — ${r.team.nama_tim}`:'-'}</td><td className="p-3">{r.row.tanggal_pelaksanaan_audit?formatTanggal(r.row.tanggal_pelaksanaan_audit):'-'}</td><td className="p-3"><Badge variant={badge[r.status_agenda]}>{r.status_agenda}</Badge></td><td className="p-3"><Button size="sm" disabled={busy||(readOnly&&!r.agenda)} onClick={()=>void open(r)}>{!r.agenda?(readOnly?'Belum tersedia':'Buat Agenda'):r.agenda.status==='Final'?'Lihat Agenda':'Buka Agenda'}</Button></td></tr>)}</tbody></table></Card>}
  </div>;
}

function AgendaDetail({context,initialItems,forceReadOnly,onBack,onAgendaChange}:{context:AgendaWorklistRow;initialItems:AuditAgendaItem[];forceReadOnly:boolean;onBack:()=>void;onAgendaChange:(value:AuditAgenda)=>void}){
  const [form,setForm]=useState<AuditAgenda>(context.agenda as AuditAgenda); const [timeline,setTimeline]=useState<TimelineDraftItem[]>(initialItems.map(toDraftItem)); const [dirty,setDirty]=useState(false); const [busy,setBusy]=useState(false); const [error,setError]=useState<string|null>(null);
  const readOnly=forceReadOnly||form.status==='Final';
  const update=(key:keyof AuditAgenda,value:unknown)=>{setForm(old=>({...old,[key]:value}));setDirty(true);};
  const changeTimeline=(client:string,patch:Partial<TimelineDraftItem>)=>{setTimeline(old=>old.map(item=>item.client_id===client?{...item,...patch}:item));setDirty(true);};
  const effective=useMemo(()=>{const result=new Map<string,string>();let last='';timeline.forEach(item=>{if(item.lokasi?.trim())last=item.lokasi.trim();result.set(item.client_id,last);});return result;},[timeline]);
  function add(){setTimeline(old=>[...old,{client_id:clientId(),tanggal:context.row.tanggal_pelaksanaan_audit??toDateInput(new Date()),jam_mulai:'08:00',jam_selesai:'09:00',detail_audit_proses_persyaratan:'',lokasi:null}]);setDirty(true);}
  function remove(client:string){setTimeline(old=>old.filter(item=>item.client_id!==client));setDirty(true);}
  function move(index:number,delta:number){const target=index+delta;if(target<0||target>=timeline.length)return;setTimeline(old=>{const next=[...old];[next[index],next[target]]=[next[target],next[index]];return next;});setDirty(true);}
  function validate(){for(const item of timeline){if(!item.tanggal||!item.jam_mulai||!item.jam_selesai||!item.detail_audit_proses_persyaratan.trim())throw new Error('Tanggal, waktu, dan Detail Audit wajib diisi untuk setiap kegiatan');if(item.jam_selesai<=item.jam_mulai)throw new Error('Jam Selesai harus lebih akhir dari Jam Mulai');}}
  async function save(){validate();const result=await saveAgendaDraftBundle(form,timeline.map(({tanggal,jam_mulai,jam_selesai,detail_audit_proses_persyaratan,lokasi})=>({tanggal,jam_mulai,jam_selesai,detail_audit_proses_persyaratan,lokasi})));setForm(result.agenda);setTimeline(result.items.map(toDraftItem));setDirty(false);onAgendaChange(result.agenda);return result.agenda;}
  async function action(task:()=>Promise<void>){setBusy(true);setError(null);try{await task();}catch(e){setError(e instanceof Error?e.message:'Operasi Agenda gagal');}finally{setBusy(false);}}
  function back(){if(dirty&&!window.confirm('Perubahan Agenda belum disimpan. Tetap kembali?'))return;onBack();}
  return <div className="max-w-6xl mx-auto"><button onClick={back} className="mb-4 text-sm text-blue-700 flex gap-1"><ArrowLeft size={16}/> Kembali ke Worklist</button>
    {error&&<div className="mb-4 p-3 bg-red-50 border border-red-200 rounded text-sm text-red-700">{error}</div>}
    <Card className="p-6 print:shadow-none"><div className="flex justify-between border-b pb-4 mb-5"><div><p className="text-xs font-semibold text-blue-700">DOKUMEN AUDIT</p><h1 className="text-2xl font-bold">AGENDA INTERNAL AUDIT</h1>{dirty&&<p className="text-xs text-amber-600 mt-1">Perubahan belum disimpan</p>}</div><div className="text-right"><Badge variant={form.status==='Final'?'green':'blue'}>{form.status}</Badge><p className="text-xs text-gray-500 mt-2">{KODE_DOKUMEN_AGENDA_INTERNAL_AUDIT}</p></div></div>
    <section className="mb-6"><SectionTitle title="Informasi Audit" auto/><div className="grid md:grid-cols-3 gap-3"><Read label="No. Audit" value={context.row.kode_audit}/><Read label="Proses yang Diaudit" value={context.proses?.nama_proses}/><Read label="Tipe Audit" value={context.row.tipe_baris}/><Read label="Seksi yang Diaudit" value={context.seksi.map(s=>s.nama).join(', ')}/><Read label="Manager Seksi/Proses" value={context.managers.join(', ')}/><Read label="Tanggal Pelaksanaan" value={context.row.tanggal_pelaksanaan_audit?formatTanggal(context.row.tanggal_pelaksanaan_audit):undefined}/></div></section>
    <section className="mb-6"><SectionTitle title="Data Agenda"/><div className="grid md:grid-cols-2 gap-4"><label className="text-sm font-medium">Tanggal Terbit<Input type="date" disabled={readOnly} value={form.tanggal_terbit} onChange={e=>update('tanggal_terbit',e.target.value)}/></label><label className="text-sm font-medium md:col-span-2">Tujuan dan Lingkup Audit<Textarea disabled={readOnly} value={form.tujuan_lingkup_audit??''} onChange={e=>update('tujuan_lingkup_audit',e.target.value)}/></label></div></section>
    <section className="mb-6"><SectionTitle title="Audit Team" auto/><div className="grid md:grid-cols-3 gap-3"><Read label="Team Audit" value={context.team?`${context.team.kode_tim} — ${context.team.nama_tim}`:undefined}/><Read label="Lead Auditor" value={context.lead?.nama}/><Read label="Member Auditor" value={context.members.map(a=>a.nama).join(', ')}/></div><AssistantEditor value={form.asisten_auditor_pendamping} disabled={readOnly} onChange={v=>update('asisten_auditor_pendamping',v)}/><label className="block text-sm font-medium mt-4">Item Lain yang Dicek<Textarea disabled={readOnly} value={form.item_lain_yang_dicek??''} onChange={e=>update('item_lain_yang_dicek',e.target.value)}/></label></section>
    <section className="mb-6"><SectionTitle title="Dokumen"/><div className="grid md:grid-cols-2 gap-4"><label className="text-sm font-medium">Dokumen yang Dikirim di Awal<Textarea disabled={readOnly} value={form.dokumen_dikirim_di_awal??''} onChange={e=>update('dokumen_dikirim_di_awal',e.target.value)}/></label><label className="text-sm font-medium">Dokumen yang Dipersiapkan di Hari Audit<Textarea disabled={readOnly} value={form.dokumen_dipersiapkan_hari_audit??''} onChange={e=>update('dokumen_dipersiapkan_hari_audit',e.target.value)}/></label></div></section>
    <section className="mb-6"><div className="flex justify-between"><SectionTitle title="Timeline Audit"/>{!readOnly&&<Button size="sm" onClick={add}><Plus size={14}/> Tambah Kegiatan</Button>}</div>{!timeline.length?<p className="text-sm text-gray-500 border rounded p-4">Belum ada kegiatan audit. Klik Tambah Kegiatan untuk mulai menyusun timeline.</p>:<div className="space-y-2">{timeline.map((item,index)=><TimelineRow key={item.client_id} value={item} effective={effective.get(item.client_id)||''} disabled={readOnly} onChange={patch=>changeTimeline(item.client_id,patch)} onDelete={()=>remove(item.client_id)} onUp={()=>move(index,-1)} onDown={()=>move(index,1)}/>)}</div>}</section>
    <section><SectionTitle title="Catatan Khusus"/><Textarea disabled={readOnly} value={form.catatan_khusus??''} onChange={e=>update('catatan_khusus',e.target.value)}/></section>
    <div className="flex justify-end gap-2 mt-6 pt-4 border-t">{!readOnly&&<><Button variant="secondary" disabled={busy} onClick={()=>void action(async()=>{await save();})}>Simpan Agenda</Button><Button disabled={busy} onClick={()=>void action(async()=>{const saved=await save();const final=await finalizeAgenda(saved.id);setForm(final);setDirty(false);onAgendaChange(final);})}>Finalkan Agenda</Button></>}{readOnly&&<Button disabled={busy} onClick={()=>void action(async()=>{const reopened=await returnAgendaToDraft(form.id);const items=await listAgendaItems(form.id);setForm(reopened);setTimeline(items.map(toDraftItem));setDirty(false);onAgendaChange(reopened);})}>Kembalikan ke Draft</Button>}</div>
    </Card></div>;
}
function SectionTitle({title,auto=false}:{title:string;auto?:boolean}){return <div className="flex gap-2 items-center mb-3 border-b pb-2"><h2 className="font-semibold text-gray-800">{title}</h2>{auto&&<span className="text-[10px] bg-blue-50 text-blue-700 px-2 py-0.5 rounded">AUTO / READ-ONLY</span>}</div>}
function Read({label,value}:{label:string;value?:string|null}){return <div className="bg-gray-50 border rounded p-3"><p className="text-xs text-gray-500">{label}</p><p className="text-sm font-medium mt-1">{value||'-'}</p></div>}
function AssistantEditor({value,disabled,onChange}:{value:AgendaAssistantAuditor[];disabled:boolean;onChange:(v:AgendaAssistantAuditor[])=>void}){return <div className="mt-4"><div className="flex justify-between"><p className="text-sm font-medium">Asisten Auditor Pendamping / Seksi (opsional)</p>{!disabled&&<button className="text-xs text-blue-700" onClick={()=>onChange([...value,{nama:'',seksi:''}])}>+ Tambah Asisten</button>}</div>{value.map((a,i)=><div key={i} className="grid grid-cols-[1fr_1fr_auto] gap-2 mt-2"><Input disabled={disabled} placeholder="Nama" value={a.nama} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,nama:e.target.value}:x))}/><Input disabled={disabled} placeholder="Seksi" value={a.seksi} onChange={e=>onChange(value.map((x,j)=>j===i?{...x,seksi:e.target.value}:x))}/>{!disabled&&<button title="Hapus asisten" onClick={()=>onChange(value.filter((_,j)=>j!==i))}><Trash2 size={15}/></button>}</div>)}</div>}
function TimelineRow({value,effective,disabled,onChange,onDelete,onUp,onDown}:{value:TimelineDraftItem;effective:string;disabled:boolean;onChange:(v:Partial<TimelineDraftItem>)=>void;onDelete:()=>void;onUp:()=>void;onDown:()=>void}){return <div className="grid lg:grid-cols-[130px_100px_100px_1fr_180px_auto] gap-2 border rounded p-2 items-end"><Input type="date" disabled={disabled} value={value.tanggal} onChange={e=>onChange({tanggal:e.target.value})}/><Input type="time" disabled={disabled} value={value.jam_mulai} onChange={e=>onChange({jam_mulai:e.target.value})}/><Input type="time" disabled={disabled} value={value.jam_selesai} onChange={e=>onChange({jam_selesai:e.target.value})}/><Input disabled={disabled} placeholder="Detail Audit (Proses/Persyaratan)" value={value.detail_audit_proses_persyaratan} onChange={e=>onChange({detail_audit_proses_persyaratan:e.target.value})}/><div><Input disabled={disabled} placeholder="Mengikuti lokasi baris sebelumnya" value={value.lokasi??''} onChange={e=>onChange({lokasi:e.target.value||null})}/>{!value.lokasi&&effective&&<p className="text-[10px] text-gray-500 mt-1">Efektif: {effective}</p>}</div>{!disabled&&<div className="flex gap-2 pb-2"><button title="Pindah ke atas" onClick={onUp}><ArrowUp size={15}/></button><button title="Pindah ke bawah" onClick={onDown}><ArrowDown size={15}/></button><button title="Hapus kegiatan" className="text-red-600" onClick={onDelete}><Trash2 size={15}/></button></div>}</div>}
