import { useCallback,useEffect,useState,type ReactNode } from 'react';
import { ArrowLeft,FileText,Plus,RefreshCw,Trash2 } from 'lucide-react';
import type { InternalAuditReport,InternalAuditReportAttendee,InternalAuditReportContext,InternalAuditReportFollowUpItem,InternalAuditReportWorklistRow } from '../../lib/types';
import { createInternalAuditReport,generateEvaluasiDraft,generateHasilPengamatanDraft,getInternalAuditReportContext,listInternalAuditReportWorklist,saveInternalAuditReportDraft } from '../../services/internalAuditReportService';
import { Badge,Button,Card,EmptyState,LoadingSpinner,PageHeader } from '../ui';
import { Field,Input,Select,Textarea } from '../ui/Field';

export function LaporanInternalAuditPage(){
  const [rows,setRows]=useState<InternalAuditReportWorklistRow[]>([]);
  const [selected,setSelected]=useState<InternalAuditReportContext|null>(null);
  const [loading,setLoading]=useState(true);
  const [busy,setBusy]=useState(false);
  const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError(null);try{setRows(await listInternalAuditReportWorklist());}catch(error){setError(message(error));}finally{setLoading(false);}},[]);
  useEffect(()=>{void load();},[load]);
  async function open(rowId:string){setBusy(true);setError(null);try{setSelected(await getInternalAuditReportContext(rowId));}catch(error){setError(message(error));}finally{setBusy(false);}}
  async function create(rowId:string){setBusy(true);setError(null);try{await createInternalAuditReport(rowId);await open(rowId);}catch(error){setError(message(error));setBusy(false);}}
  if(loading)return <LoadingSpinner message="Memuat workspace Laporan Internal Audit..."/>;
  if(selected?.report)return <DraftEditor context={selected} onBack={async()=>{setSelected(null);await load();}} onReload={()=>open(selected.row.id)}/>;
  return <div><PageHeader title="Laporan Internal Audit" subtitle="Foundation dan penyusunan Draft Q-120-ISE-001-FORM-015" actions={<Button variant="secondary" onClick={()=>void load()}><RefreshCw size={15}/>Muat Ulang</Button>}/>
    {error&&<ErrorBox value={error}/>}<Card className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead className="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr>{['No. Audit','Proses','Agenda','Checklist','Temuan','Status Laporan','Aksi'].map(value=><th key={value} className="px-4 py-3">{value}</th>)}</tr></thead><tbody className="divide-y">
      {rows.map(row=>{const types=[row.checklist_presence.sistem&&'Sistem',row.checklist_presence.produk&&'Produk',row.checklist_presence.manufaktur_shift&&'Manufaktur/Shift'].filter(Boolean);return <tr key={row.row.id} className="align-top"><td className="px-4 py-3 font-semibold text-blue-800">{row.row.kode_audit}</td><td className="px-4 py-3">{row.proses?.nama_proses||'-'}</td><td className="px-4 py-3"><Badge variant={row.agenda?'blue':'gray'}>{row.agenda?.status||'Belum Dibuat'}</Badge></td><td className="px-4 py-3">{types.length?types.join(', '):'Belum tersedia'}</td><td className="px-4 py-3 text-xs leading-5"><div>Major: {row.finding_counts.A}</div><div>Minor: {row.finding_counts.B}</div><div>Peluang Improvement: {row.finding_counts.C}</div></td><td className="px-4 py-3"><Badge variant={row.report?.status==='Final'?'green':row.report?'amber':'gray'}>{row.report?.status||'Belum Dibuat'}</Badge></td><td className="px-4 py-3"><Button size="sm" disabled={busy||(!row.report&&!row.eligible)} onClick={()=>void(row.report?open(row.row.id):create(row.row.id))}>{row.report?'Buka Laporan':'Buat Laporan'}</Button>{!row.report&&row.eligibility_reason&&<p className="mt-2 max-w-48 text-xs text-amber-700">{row.eligibility_reason}</p>}</td></tr>;})}
    </tbody></table>{!rows.length&&<EmptyState icon={<FileText/>} title="Belum ada baris Instruksi Audit" message="Baris Instruksi Audit akan ditampilkan termasuk yang belum memenuhi eligibility."/>}</Card></div>;
}

interface DraftForm { tanggal_terbit:string;auditee_hadir:InternalAuditReportAttendee[];nama_customer:string;nama_produk:string;nama_line:string;sub_leader_auditor_id:string;hasil_pengamatan:string;evaluasi:string;follow_up_required:''|'true'|'false';follow_up_items:InternalAuditReportFollowUpItem[];catatan:string; }
const toForm=(value:InternalAuditReport):DraftForm=>({tanggal_terbit:value.tanggal_terbit,auditee_hadir:value.auditee_hadir,nama_customer:value.nama_customer??'',nama_produk:value.nama_produk??'',nama_line:value.nama_line??'',sub_leader_auditor_id:value.sub_leader_auditor_id??'',hasil_pengamatan:value.hasil_pengamatan,evaluasi:value.evaluasi,follow_up_required:value.follow_up_required===null?'':String(value.follow_up_required) as 'true'|'false',follow_up_items:value.follow_up_items,catatan:value.catatan??''});

function DraftEditor({context,onBack,onReload}:{context:InternalAuditReportContext;onBack:()=>void|Promise<void>;onReload:()=>void|Promise<void>}){
  const [report,setReport]=useState(context.report!);const [form,setForm]=useState(()=>toForm(context.report!));const [busy,setBusy]=useState(false);const [notice,setNotice]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);
  useEffect(()=>{if(context.report){setReport(context.report);setForm(toForm(context.report));setNotice(null);setError(null);}},[context.report]);
  function patch<K extends keyof DraftForm>(key:K,value:DraftForm[K]){setForm(current=>({...current,[key]:value}));setNotice(null);}
  async function save(){setBusy(true);setError(null);setNotice(null);try{const saved=await saveInternalAuditReportDraft({report_id:report.id,expected_revision:report.revision_version,tanggal_terbit:form.tanggal_terbit,auditee_hadir:form.auditee_hadir,nama_customer:form.nama_customer,nama_produk:form.nama_produk,nama_line:form.nama_line,sub_leader_auditor_id:form.sub_leader_auditor_id||null,hasil_pengamatan:form.hasil_pengamatan,evaluasi:form.evaluasi,follow_up_required:form.follow_up_required===''?null:form.follow_up_required==='true',follow_up_items:form.follow_up_items,catatan:form.catatan});setReport(saved);setForm(toForm(saved));setNotice(`Draft tersimpan. Revisi ${saved.revision_version}.`);}catch(error){setError(message(error));}finally{setBusy(false);}}
  const members=context.team_members.filter(value=>value.id!==form.sub_leader_auditor_id);
  return <div><PageHeader title={`Laporan Internal Audit — ${context.row.kode_audit}`} subtitle={`Status Draft · Revisi ${report.revision_version} · ${report.kode_dokumen}`} actions={<><Button variant="ghost" onClick={()=>void onBack()}><ArrowLeft size={15}/>Kembali</Button><Button variant="secondary" onClick={()=>void onReload()}><RefreshCw size={15}/>Muat Ulang</Button></>}/>{error&&<ErrorBox value={error}/>} {notice&&<div className="mb-4 rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-700">{notice}</div>}
    <Section title="Konteks Audit" computed><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><Read label="No. Audit" value={context.row.kode_audit}/><Field label="Tanggal Terbit" required><Input type="date" value={form.tanggal_terbit} onChange={event=>patch('tanggal_terbit',event.target.value)}/></Field><Read label="Proses yang Diaudit" value={context.proses?.nama_proses}/><Read label="Manager Seksi yang Diaudit" value={context.sections.map(value=>`${value.nama}: ${value.kepala_seksi||'-'}`).join('; ')}/><Read label="Tujuan & Lingkup Audit" value={context.agenda?.tujuan_lingkup_audit}/><Read label="Waktu & Tanggal Audit" value={context.audit_time_range}/></div></Section>
    <Section title="Audit Team" computed><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><Read label="Kode Team" value={context.team?.kode_tim}/><Read label="Team Leader" value={context.team_leader?.nama}/><Field label="Sub Leader (opsional)"><Select value={form.sub_leader_auditor_id} onChange={event=>patch('sub_leader_auditor_id',event.target.value)}><option value="">Tidak ada Sub Leader</option>{context.team_members.map(value=><option key={value.id} value={value.id}>{value.nama}{value.departemen?` — ${value.departemen}`:''}</option>)}</Select></Field><Read label="Member Audit" value={members.map(value=>value.nama).join(', ')}/><Read label="Asisten Auditor Pendamping" value={context.agenda?.asisten_auditor_pendamping.map(value=>`${value.nama}${value.seksi?` (${value.seksi})`:''}`).join(', ')}/><Read label="Item Lain yang Dicek" value={context.agenda?.item_lain_yang_dicek}/></div></Section>
    <Section title="Auditee Hadir"><div className="flex justify-end mb-3"><Button size="sm" variant="secondary" onClick={()=>patch('auditee_hadir',[...form.auditee_hadir,{nama:'',seksi:''}])}><Plus size={14}/>Tambah Auditee</Button></div>{form.auditee_hadir.length===0?<p className="text-sm text-gray-500">Belum ada auditee hadir. Draft tetap dapat disimpan.</p>:form.auditee_hadir.map((value,index)=><div key={index} className="mb-2 grid grid-cols-[1fr_1fr_auto] gap-2"><Input placeholder="Nama" value={value.nama} onChange={event=>patch('auditee_hadir',form.auditee_hadir.map((item,i)=>i===index?{...item,nama:event.target.value}:item))}/><Input placeholder="Seksi" value={value.seksi} onChange={event=>patch('auditee_hadir',form.auditee_hadir.map((item,i)=>i===index?{...item,seksi:event.target.value}:item))}/><Button title="Hapus auditee" variant="ghost" onClick={()=>patch('auditee_hadir',form.auditee_hadir.filter((_,i)=>i!==index))}><Trash2 size={15}/></Button></div>)}</Section>
    <Section title="Customer / Produk / Line"><div className="grid gap-3 md:grid-cols-3"><Field label="Nama Customer"><Input value={form.nama_customer} onChange={event=>patch('nama_customer',event.target.value)}/></Field><Field label="Nama Produk"><Input value={form.nama_produk} onChange={event=>patch('nama_produk',event.target.value)}/></Field><Field label="Nama Line"><Input value={form.nama_line} onChange={event=>patch('nama_line',event.target.value)}/></Field></div><p className="mt-2 text-xs text-gray-500">Saran awal diisi hanya saat pembuatan jika upstream memiliki tepat satu nilai unik; selanjutnya data ini milik laporan dan dapat diedit.</p></Section>
    <Section title="Hasil Pengamatan"><div className="mb-2 flex justify-between text-xs text-gray-600"><span>Major {context.finding_counts.A} · Minor {context.finding_counts.B} · Peluang Improvement {context.finding_counts.C}</span><Button size="sm" variant="secondary" onClick={()=>patch('hasil_pengamatan',generateHasilPengamatanDraft({proses:context.proses?.nama_proses??null,counts:context.finding_counts,nama_customer:form.nama_customer,nama_produk:form.nama_produk}))}>Generate Draft Hasil Pengamatan</Button></div><Textarea rows={5} value={form.hasil_pengamatan} onChange={event=>patch('hasil_pengamatan',event.target.value)}/></Section>
    <Section title="Evaluasi"><div className="mb-2 flex justify-end"><Button size="sm" variant="secondary" onClick={()=>patch('evaluasi',generateEvaluasiDraft({counts:context.finding_counts,references:context.finding_references}))}>Generate Draft Evaluasi</Button></div><Textarea rows={5} value={form.evaluasi} onChange={event=>patch('evaluasi',event.target.value)}/></Section>
    <Section title="Follow-up"><Field label="Saran Perbaikan / Follow-up"><Select value={form.follow_up_required} onChange={event=>{const value=event.target.value as DraftForm['follow_up_required'];setForm(current=>({...current,follow_up_required:value,follow_up_items:value==='true'?current.follow_up_items:[]}));setNotice(null);}}><option value="">Belum ditentukan</option><option value="true">Ada</option><option value="false">Tidak</option></Select></Field>{form.follow_up_required==='true'&&<div className="mt-3"><div className="flex justify-end mb-2"><Button size="sm" variant="secondary" onClick={()=>patch('follow_up_items',[...form.follow_up_items,{seksi:'',seksi_pelaksana_follow_up:'',jadwal_follow_up:null}])}><Plus size={14}/>Tambah Follow-up</Button></div>{form.follow_up_items.map((value,index)=><div key={index} className="mb-2 grid gap-2 md:grid-cols-[1fr_1fr_180px_auto]"><Input placeholder="Seksi" value={value.seksi} onChange={event=>patch('follow_up_items',form.follow_up_items.map((item,i)=>i===index?{...item,seksi:event.target.value}:item))}/><Input placeholder="Seksi pelaksana follow-up" value={value.seksi_pelaksana_follow_up} onChange={event=>patch('follow_up_items',form.follow_up_items.map((item,i)=>i===index?{...item,seksi_pelaksana_follow_up:event.target.value}:item))}/><Input type="date" value={value.jadwal_follow_up??''} onChange={event=>patch('follow_up_items',form.follow_up_items.map((item,i)=>i===index?{...item,jadwal_follow_up:event.target.value||null}:item))}/><Button variant="ghost" title="Hapus follow-up" onClick={()=>patch('follow_up_items',form.follow_up_items.filter((_,i)=>i!==index))}><Trash2 size={15}/></Button></div>)}</div>}</Section>
    <Section title="Catatan"><Textarea rows={4} value={form.catatan} onChange={event=>patch('catatan',event.target.value)}/></Section>
    <div className="sticky bottom-0 flex justify-end border-t bg-gray-100/95 py-4"><Button disabled={busy} onClick={()=>void save()}>{busy?'Menyimpan...':'Simpan Draft'}</Button></div></div>;
}

function Section({title,computed=false,children}:{title:string;computed?:boolean;children:ReactNode}){return <Card className="mb-5 p-5"><div className="mb-4 flex items-center gap-2 border-b pb-2"><h2 className="font-semibold text-gray-800">{title}</h2>{computed&&<Badge variant="blue">AUTO / READ-ONLY</Badge>}</div>{children}</Card>}
function Read({label,value}:{label:string;value?:string|null}){return <div className="rounded-lg border bg-gray-50 p-3"><p className="text-xs text-gray-500">{label}</p><p className="mt-1 whitespace-pre-wrap text-sm font-medium">{value?.trim()||'-'}</p></div>}
function ErrorBox({value}:{value:string}){return <div className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{value}</div>}
function message(error:unknown){return error instanceof Error?error.message:'Terjadi kesalahan saat memproses Laporan Internal Audit.';}
