import { useCallback,useEffect,useMemo,useState } from 'react';
import { ArrowLeft,AlertTriangle } from 'lucide-react';
import type { Finding,FindingCapabilities,FindingContext,FindingNotification,FindingReviewEvent,FindingSourceDisposition } from '../../lib/types';
import { KLASIFIKASI_DIS,KATEGORI_TEMUAN_LABEL } from '../../lib/enums';
import { formatFindingNarrative,isFindingPLORComplete } from '../../lib/finding';
import { addFindingTeamResponse,findingTeamAuditors,getClauseSuggestions,getFindingContext,getFindingWorkflow,listFindings,listOwnFindingNotifications,markFindingNotificationRead,saveFindingPLOR,transitionFinding } from '../../services/findingService';
import { Badge,Button,Card,EmptyState,LoadingSpinner } from '../ui';
import { Field,Input,Select,Textarea } from '../ui/Field';

const sourceLabel:Record<string,string>={ChecklistSistem:'Sistem',ChecklistProduk:'Produk',ChecklistManufakturShift:'Manufaktur / Shift'};
export function TemuanPage(){
 const [items,setItems]=useState<Finding[]>([]),[notifications,setNotifications]=useState<FindingNotification[]>([]),[selected,setSelected]=useState<string|null>(null),[search,setSearch]=useState(''),[source,setSource]=useState(''),[category,setCategory]=useState(''),[reviewStatus,setReviewStatus]=useState(''),[status,setStatus]=useState(''),[complete,setComplete]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[success,setSuccess]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{const[f,n]=await Promise.all([listFindings(),listOwnFindingNotifications()]);setItems(f);setNotifications(n);setError(null);}catch(e){setError(e instanceof Error?e.message:'Gagal memuat Temuan');}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);
 const filtered=useMemo(()=>items.filter(f=>(!search||`${f.kode_temuan??f.draft_reference} ${f.kode_audit}`.toLowerCase().includes(search.toLowerCase()))&&(!source||f.source_type===source)&&(!category||f.kategori===category)&&(!reviewStatus||f.review_status===reviewStatus)&&(!status||f.status===status)&&(!complete||(isFindingPLORComplete(f)?'Lengkap':'Belum Lengkap')===complete)),[items,search,source,category,reviewStatus,status,complete]);
 if(loading)return <LoadingSpinner message="Memuat Temuan / PLOR..."/>;if(selected)return <FindingDetail id={selected} onBack={()=>{setSelected(null);load();}} onSaved={()=>{setSuccess('PLOR berhasil disimpan.');setSelected(null);load();}}/>;
 return <div><h1 className="text-2xl font-bold">Temuan (PLOR)</h1><p className="text-sm text-gray-500 mb-6">Workspace formal Temuan. Temuan dibuat otomatis dari hasil Checklist.</p>{success&&<div className="p-3 mb-4 bg-green-50 text-green-700">{success}</div>}{error&&<div className="p-3 mb-4 bg-red-50 text-red-700">{error}</div>}{notifications.some(n=>!n.read_at)&&<Card className="p-4 mb-4"><h2 className="font-semibold mb-2">Notifikasi Finding</h2>{notifications.filter(n=>!n.read_at).map(n=><button key={n.id} className="block w-full text-left border-t py-2" onClick={()=>{void markFindingNotificationRead(n.id);if(n.finding_id)setSelected(n.finding_id);}}><b>{n.title}</b><div className="text-sm text-gray-600 whitespace-pre-wrap">{n.message}</div></button>)}</Card>}
 <Card className="p-4 mb-4"><div className="grid md:grid-cols-6 gap-3"><Input placeholder="Cari Kode Temuan / QA" value={search} onChange={e=>setSearch(e.target.value)}/><Select value={source} onChange={e=>setSource(e.target.value)}><option value="">Semua Sumber</option>{Object.entries(sourceLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Semua Kategori</option>{['A','B','C'].map(v=><option key={v}>{v}</option>)}</Select><Select value={reviewStatus} onChange={e=>setReviewStatus(e.target.value)}><option value="">Semua Status Review</option>{['DRAFT','LEAD_REVIEW','REVISION_REQUIRED','READY_FOR_RELEASE','PUBLISHED','ANNULLED','LEGACY_ESTABLISHED'].map(v=><option key={v}>{v}</option>)}</Select><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua Status Finding/CAR</option>{['Open','CAR Submitted','Verifikasi','Closed','Overdue'].map(v=><option key={v}>{v}</option>)}</Select><Select value={complete} onChange={e=>setComplete(e.target.value)}><option value="">Semua PLOR</option><option>Lengkap</option><option>Belum Lengkap</option></Select></div></Card>
 {!filtered.length?<Card className="p-12"><EmptyState icon={<AlertTriangle/>} title="Belum ada Temuan" message="Temuan akan dibuat otomatis saat hasil Checklist memicu kategori A, B, atau C."/></Card>:<Card className="overflow-x-auto"><table className="min-w-[1200px] w-full text-xs"><thead><tr className="bg-gray-50 text-left">{['Kode Temuan','No. Audit','Proses / Auditee Area','Sumber','Kategori','PLOR','Auditor Penemu','Tanggal Temuan','Review Status','Finding / CAR Status','Aksi'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{filtered.map(f=><tr key={f.id} className="border-t"><td className="p-3 font-mono font-semibold">{f.kode_temuan??f.draft_reference}</td><td>{f.kode_audit}</td><td>{f.auditee_area||'-'}</td><td>{sourceLabel[f.source_type]}</td><td>{KATEGORI_TEMUAN_LABEL[f.kategori]}</td><td><Badge variant={isFindingPLORComplete(f)?'green':'amber'}>{isFindingPLORComplete(f)?'Lengkap':'Belum Lengkap'}</Badge></td><td>{f.auditor_penemu?.nama||'-'}</td><td>{new Date(`${f.tanggal_temuan}T00:00:00`).toLocaleDateString('id-ID')}</td><td><Badge variant="gray">{f.review_status}</Badge></td><td><Badge variant="gray">{f.status}</Badge></td><td><Button size="sm" onClick={()=>setSelected(f.id)}>Buka PLOR</Button></td></tr>)}</tbody></table></Card>}</div>;
}
function FindingDetail({id,onBack,onSaved}:{id:string;onBack:()=>void;onSaved:()=>void}){const [ctx,setCtx]=useState<FindingContext|null>(null),[form,setForm]=useState<Finding|null>(null),[cap,setCap]=useState<FindingCapabilities|null>(null),[events,setEvents]=useState<FindingReviewEvent[]>([]),[disposition,setDisposition]=useState<FindingSourceDisposition|null>(null),[suggestions,setSuggestions]=useState<{id:string;klausul:string;keyword:string}[]>([]),[error,setError]=useState<string|null>(null),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false);const reload=useCallback(async()=>{const[c,w]=await Promise.all([getFindingContext(id),getFindingWorkflow(id)]);setCtx(c);setForm(c.finding);setCap(w.capabilities);setEvents(w.events);setDisposition(w.disposition);},[id]);useEffect(()=>{setLoading(true);setError(null);reload().catch(e=>setError(e instanceof Error?e.message:'Gagal memuat detail Temuan')).finally(()=>setLoading(false));},[reload]);const problem=form?.problem??null;useEffect(()=>{getClauseSuggestions(problem).then(setSuggestions).catch(e=>setError(e instanceof Error?e.message:'Gagal memuat saran klausul'));},[problem]);if(loading)return <LoadingSpinner message="Memuat detail Temuan..."/>;if(error&&(!ctx||!form))return <div><Button variant="secondary" className="mb-4" onClick={onBack}><ArrowLeft size={14}/> Kembali</Button><div className="p-3 bg-red-50 text-red-700">{error}</div></div>;if(!ctx||!form)return <div><Button variant="secondary" className="mb-4" onClick={onBack}><ArrowLeft size={14}/> Kembali</Button><div className="p-3 bg-red-50 text-red-700">Detail Temuan tidak tersedia.</div></div>;const set=<K extends keyof Finding>(key:K,value:Finding[K])=>setForm({...form,[key]:value});const auditors=findingTeamAuditors(ctx);async function save(){setSaving(true);try{await saveFindingPLOR(form!);setError(null);onSaved();}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan');}finally{setSaving(false);}}
 const editable=Boolean(cap&&(cap.is_admin||cap.is_team_member)&&['DRAFT','REVISION_REQUIRED'].includes(form.review_status));const locked=ctx.row.cek_selesai||!editable;
 return <div><Button variant="secondary" className="mb-4" onClick={onBack}><ArrowLeft size={14}/> Kembali</Button>{error&&<div className="p-3 mb-4 bg-red-50 text-red-700">{error}</div>}{ctx.row.cek_selesai&&<div className="p-3 mb-4 rounded-lg border border-blue-200 bg-blue-50 text-sm text-blue-700">Pelaksanaan audit ini sudah selesai.</div>}{!ctx.row.cek_selesai&&!editable&&<div className="p-3 mb-4 rounded-lg border border-gray-200 bg-gray-50 text-sm text-gray-700">PLOR read-only pada tahap review ini.</div>}<div className="space-y-4"><Card className="p-5"><h2 className="font-semibold mb-3">1. Identitas Temuan — Read-only</h2><div className="grid md:grid-cols-4 gap-3 text-sm"><Info l={form.kode_temuan?"Kode Temuan Resmi":"Referensi Draft"} v={form.kode_temuan??form.draft_reference}/><Info l="QA" v={form.kode_audit}/><Info l="Sumber" v={sourceLabel[form.source_type]}/><Info l="Kategori" v={KATEGORI_TEMUAN_LABEL[form.kategori]}/><Info l="Review Status" v={form.review_status}/><Info l="Finding / CAR Status" v={form.status}/><Info l="Proses" v={ctx.proses?.nama_proses}/><Info l="Sections" v={ctx.sections.map(s=>s.nama).join(', ')}/><Info l="Tanggal Pelaksanaan" v={ctx.row.tanggal_pelaksanaan_audit}/></div></Card>
 <Card className="p-5 border-l-4 border-amber-400"><h2 className="font-semibold">2. Sumber Checklist — Read-only</h2><p className="text-xs text-gray-500 mb-3">Catatan kerja sumber bukan Problem formal dan tidak disalin otomatis ke PLOR.</p><div className="grid md:grid-cols-3 gap-2">{Object.entries(ctx.source_details).filter(([,v])=>typeof v!=='object').map(([k,v])=><Info key={k} l={k.replace(/_/g,' ')} v={v as string|number|null}/>)}</div><div className="mt-4 p-3 bg-amber-50"><div className="text-xs font-bold uppercase">Catatan Sumber Checklist</div><div className="whitespace-pre-wrap">{ctx.source_note||'-'}</div></div></Card>
 <fieldset disabled={locked} className="space-y-4"><Card className="p-5"><h2 className="font-semibold mb-3">3. Auditor / Area</h2><div className="grid md:grid-cols-4 gap-3"><Field label="Auditor Penemu"><Select value={form.auditor_penemu_id??''} onChange={e=>set('auditor_penemu_id',e.target.value||null)}><option value="">— Pilih —</option>{auditors.map(a=><option key={a.id} value={a.id}>{a.nama}</option>)}</Select></Field><Field label="Auditee Area"><Input value={form.auditee_area??''} onChange={e=>set('auditee_area',e.target.value||null)}/></Field><Field label="Tanggal Temuan"><Input type="date" value={form.tanggal_temuan} onChange={e=>set('tanggal_temuan',e.target.value)}/></Field><Field label="Klasifikasi DIS"><Select value={form.klasifikasi_dis??''} onChange={e=>set('klasifikasi_dis',(e.target.value||null) as Finding['klasifikasi_dis'])}><option value="">— Opsional —</option>{Object.values(KLASIFIKASI_DIS).map(v=><option key={v}>{v}</option>)}</Select></Field></div></Card>
 <Card className="p-5"><h2 className="font-semibold mb-3">4. PLOR Formal</h2>{form.kategori==='C'?<div className="space-y-3"><Field label="Kondisi / Peluang Peningkatan *"><Textarea value={form.problem??''} onChange={e=>set('problem',e.target.value||null)}/><p className="text-xs text-gray-500 mt-1">Jelaskan kondisi yang dapat ditingkatkan tanpa menyatakan ketidaksesuaian formal.</p></Field><Field label="Location *"><Textarea value={form.location??''} onChange={e=>set('location',e.target.value||null)}/></Field><Field label="Objective Evidence *"><Textarea value={form.objective_evidence??''} onChange={e=>set('objective_evidence',e.target.value||null)}/></Field><Field label="Saran Perbaikan *"><Textarea value={form.saran_perbaikan??''} onChange={e=>set('saran_perbaikan',e.target.value||null)}/><p className="text-xs text-gray-500 mt-1">Tuliskan rekomendasi atau peluang peningkatan yang disarankan.</p></Field><Field label="Reference / Acuan"><Textarea value={form.reference??''} onChange={e=>set('reference',e.target.value||null)}/><p className="text-xs text-gray-500 mt-1">Opsional. Isi klausul, aturan internal, atau acuan lain jika relevan.</p></Field></div>:<div className="grid md:grid-cols-2 gap-3"><Field label="Problem *"><Textarea value={form.problem??''} onChange={e=>set('problem',e.target.value||null)}/></Field><Field label="Location *"><Textarea value={form.location??''} onChange={e=>set('location',e.target.value||null)}/></Field><Field label="Objective Evidence *"><Textarea value={form.objective_evidence??''} onChange={e=>set('objective_evidence',e.target.value||null)}/></Field><Field label="Reference *"><Textarea value={form.reference??''} onChange={e=>set('reference',e.target.value||null)}/></Field></div>}</Card>
 <Card className="p-5"><h2 className="font-semibold mb-3">5. Reference / Clause Suggestions</h2>{ctx.source_reference&&<div className="mb-2">Saran Referensi dari Checklist: <Badge variant="gray">{ctx.source_reference}</Badge> {!locked&&<Button size="sm" variant="secondary" onClick={()=>set('reference',ctx.source_reference)}>Gunakan</Button>}</div>}{suggestions.map(s=><span key={s.id} className="mr-2">Saran Klausul: <Badge variant="blue">{s.klausul}</Badge> {!locked&&<Button size="sm" variant="secondary" onClick={()=>set('reference',s.klausul)}>Gunakan</Button>}</span>)}</Card></fieldset>
 <Card className="p-5"><h2 className="font-semibold">6. Narrative Preview</h2><Badge variant={isFindingPLORComplete(form)?'green':'amber'}>{isFindingPLORComplete(form)?'Lengkap':'Belum Lengkap'}</Badge><p className="mt-3 whitespace-pre-wrap">{formatFindingNarrative(form)}</p></Card><WorkflowPanel finding={form} capabilities={cap} events={events} disposition={disposition} onChanged={reload} onError={setError}/>{!locked&&<div className="flex justify-end"><Button disabled={saving} onClick={save}>{saving?'Menyimpan...':'Simpan PLOR'}</Button></div>}</div></div>}
function Info({l,v}:{l:string;v:string|number|null|undefined}){return <div><div className="text-xs uppercase text-gray-500">{l}</div><div className="font-medium">{v??'-'}</div></div>}
function WorkflowPanel({finding,capabilities,events,disposition,onChanged,onError}:{finding:Finding;capabilities:FindingCapabilities|null;events:FindingReviewEvent[];disposition:FindingSourceDisposition|null;onChanged:()=>Promise<void>;onError:(v:string|null)=>void}){
 const [busy,setBusy]=useState(false);async function run(action:string,required=false,effective?:string){const comment=window.prompt(required?'Komentar/alasan wajib diisi:':'Komentar (opsional):')??'';if(required&&!comment.trim())return;setBusy(true);try{await transitionFinding(finding.id,action,comment,effective);await onChanged();onError(null);}catch(e){onError(e instanceof Error?e.message:'Aksi workflow gagal');}finally{setBusy(false);}}
 async function response(){const comment=window.prompt('Respons/koreksi Tim:')??'';if(!comment.trim())return;setBusy(true);try{await addFindingTeamResponse(finding.id,comment);await onChanged();}catch(e){onError(e instanceof Error?e.message:'Respons gagal');}finally{setBusy(false);}}
 return <Card className="p-5"><h2 className="font-semibold mb-3">7. Review & Approval</h2><div className="flex flex-wrap gap-2 mb-4">{capabilities?.is_team_member&&['DRAFT','REVISION_REQUIRED'].includes(finding.review_status)&&<Button variant="secondary" disabled={busy} onClick={response}>Tambah Respons Tim</Button>}{capabilities?.is_team_leader&&finding.review_status==='DRAFT'&&<Button disabled={busy} onClick={()=>run('SUBMIT')}>Submit ke Lead Auditor</Button>}{capabilities?.is_team_leader&&finding.review_status==='REVISION_REQUIRED'&&<Button disabled={busy} onClick={()=>run('RESUBMIT')}>Resubmit ke Lead Auditor</Button>}{capabilities?.is_lead_auditor&&finding.review_status==='LEAD_REVIEW'&&<><Button variant="secondary" disabled={busy} onClick={()=>run('REQUEST_REVISION',true)}>Request Revision</Button><Button variant="danger" disabled={busy} onClick={()=>run('ANNUL',true,finding.source_type==='ChecklistProduk'?'OK':'O')}>Annul</Button><Button disabled={busy} onClick={()=>run('APPROVE')}>Approve</Button></>}{capabilities?.is_admin&&finding.review_status==='READY_FOR_RELEASE'&&<Button disabled={busy} onClick={()=>run('RELEASE')}>Release ke Auditee</Button>}</div>{capabilities?.is_team_member&&!capabilities.is_team_leader&&['DRAFT','REVISION_REQUIRED'].includes(finding.review_status)&&<p className="text-sm text-amber-700 mb-3">Waiting for Team Leader submission.</p>}{disposition&&<div className="p-3 mb-3 bg-amber-50 border rounded text-sm"><b>Judgement awal:</b> {disposition.initial_judgement} → <b>efektif:</b> {disposition.effective_judgement}<br/><b>Alasan:</b> {disposition.reason}<br/><b>Ditinjau oleh:</b> {disposition.actor_display_name}<br/><b>Tanggal:</b> {new Date(disposition.created_at).toLocaleString('id-ID')}</div>}<div className="space-y-2">{events.map(e=><div key={e.id} className="border-l-2 border-blue-300 pl-3 text-sm"><b>{e.event_type}</b> · {new Date(e.created_at).toLocaleString('id-ID')}<div className="text-gray-600">{e.comment||'Tanpa komentar'}</div></div>)}{!events.length&&<p className="text-sm text-gray-500">Belum ada riwayat review.</p>}</div></Card>;
}
