import { useCallback,useEffect,useMemo,useState } from 'react';
import { ArrowLeft,AlertTriangle } from 'lucide-react';
import type { Finding,FindingContext } from '../../lib/types';
import { KLASIFIKASI_DIS,KATEGORI_TEMUAN_LABEL } from '../../lib/enums';
import { formatFindingNarrative,isFindingPLORComplete } from '../../lib/finding';
import { findingTeamAuditors,getClauseSuggestions,getFindingContext,listFindings,saveFindingPLOR } from '../../services/findingService';
import { Badge,Button,Card,EmptyState,LoadingSpinner } from '../ui';
import { Field,Input,Select,Textarea } from '../ui/Field';

const sourceLabel:Record<string,string>={ChecklistSistem:'Sistem',ChecklistProduk:'Produk',ChecklistManufakturShift:'Manufaktur / Shift'};
export function TemuanPage(){
 const [items,setItems]=useState<Finding[]>([]),[selected,setSelected]=useState<string|null>(null),[search,setSearch]=useState(''),[source,setSource]=useState(''),[category,setCategory]=useState(''),[status,setStatus]=useState(''),[complete,setComplete]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null);
 const load=useCallback(async()=>{setLoading(true);try{setItems(await listFindings());setError(null);}catch(e){setError(e instanceof Error?e.message:'Gagal memuat Temuan');}finally{setLoading(false);}},[]);useEffect(()=>{load();},[load]);
 const filtered=useMemo(()=>items.filter(f=>(!search||`${f.kode_temuan} ${f.kode_audit}`.toLowerCase().includes(search.toLowerCase()))&&(!source||f.source_type===source)&&(!category||f.kategori===category)&&(!status||f.status===status)&&(!complete||(isFindingPLORComplete(f)?'Lengkap':'Belum Lengkap')===complete)),[items,search,source,category,status,complete]);
 if(loading)return <LoadingSpinner message="Memuat Temuan / PLOR..."/>;if(selected)return <FindingDetail id={selected} onBack={()=>{setSelected(null);load();}}/>;
 return <div><h1 className="text-2xl font-bold">Temuan (PLOR)</h1><p className="text-sm text-gray-500 mb-6">Workspace formal Temuan. Temuan dibuat otomatis dari hasil Checklist.</p>{error&&<div className="p-3 mb-4 bg-red-50 text-red-700">{error}</div>}
 <Card className="p-4 mb-4"><div className="grid md:grid-cols-5 gap-3"><Input placeholder="Cari Kode Temuan / QA" value={search} onChange={e=>setSearch(e.target.value)}/><Select value={source} onChange={e=>setSource(e.target.value)}><option value="">Semua Sumber</option>{Object.entries(sourceLabel).map(([v,l])=><option key={v} value={v}>{l}</option>)}</Select><Select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Semua Kategori</option>{['A','B','C'].map(v=><option key={v}>{v}</option>)}</Select><Select value={status} onChange={e=>setStatus(e.target.value)}><option value="">Semua Status</option>{['Open','CAR Submitted','Verifikasi','Closed','Overdue'].map(v=><option key={v}>{v}</option>)}</Select><Select value={complete} onChange={e=>setComplete(e.target.value)}><option value="">Semua PLOR</option><option>Lengkap</option><option>Belum Lengkap</option></Select></div></Card>
 {!filtered.length?<Card className="p-12"><EmptyState icon={<AlertTriangle/>} title="Belum ada Temuan" message="Temuan akan dibuat otomatis saat hasil Checklist memicu kategori A, B, atau C."/></Card>:<Card className="overflow-x-auto"><table className="min-w-[1200px] w-full text-xs"><thead><tr className="bg-gray-50 text-left">{['Kode Temuan','No. Audit','Proses / Auditee Area','Sumber','Kategori','PLOR','Auditor Penemu','Tanggal Temuan','Status','Aksi'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{filtered.map(f=><tr key={f.id} className="border-t"><td className="p-3 font-mono font-semibold">{f.kode_temuan}</td><td>{f.kode_audit}</td><td>{f.auditee_area||'-'}</td><td>{sourceLabel[f.source_type]}</td><td>{KATEGORI_TEMUAN_LABEL[f.kategori]}</td><td><Badge variant={isFindingPLORComplete(f)?'green':'amber'}>{isFindingPLORComplete(f)?'Lengkap':'Belum Lengkap'}</Badge></td><td>{f.auditor_penemu?.nama||'-'}</td><td>{new Date(`${f.tanggal_temuan}T00:00:00`).toLocaleDateString('id-ID')}</td><td><Badge variant="gray">{f.status}</Badge></td><td><Button size="sm" onClick={()=>setSelected(f.id)}>Buka PLOR</Button></td></tr>)}</tbody></table></Card>}</div>;
}
function FindingDetail({id,onBack}:{id:string;onBack:()=>void}){const [ctx,setCtx]=useState<FindingContext|null>(null),[form,setForm]=useState<Finding|null>(null),[suggestions,setSuggestions]=useState<{id:string;klausul:string;keyword:string}[]>([]),[error,setError]=useState<string|null>(null),[saving,setSaving]=useState(false);useEffect(()=>{getFindingContext(id).then(c=>{setCtx(c);setForm(c.finding);}).catch(e=>setError(e.message));},[id]);useEffect(()=>{getClauseSuggestions(form?.problem??null).then(setSuggestions).catch(e=>setError(e.message));},[form?.problem]);if(!ctx||!form)return <LoadingSpinner message="Memuat detail Temuan..."/>;const set=<K extends keyof Finding>(key:K,value:Finding[K])=>setForm({...form,[key]:value});const auditors=findingTeamAuditors(ctx);async function save(){setSaving(true);try{const saved=await saveFindingPLOR(form!);setForm(saved);setError(null);}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan');}finally{setSaving(false);}}
 return <div><Button variant="secondary" className="mb-4" onClick={onBack}><ArrowLeft size={14}/> Kembali</Button>{error&&<div className="p-3 mb-4 bg-red-50 text-red-700">{error}</div>}<div className="space-y-4"><Card className="p-5"><h2 className="font-semibold mb-3">1. Identitas Temuan — Read-only</h2><div className="grid md:grid-cols-4 gap-3 text-sm"><Info l="Kode Temuan" v={form.kode_temuan}/><Info l="QA" v={form.kode_audit}/><Info l="Sumber" v={sourceLabel[form.source_type]}/><Info l="Kategori" v={KATEGORI_TEMUAN_LABEL[form.kategori]}/><Info l="Status" v={form.status}/><Info l="Proses" v={ctx.proses?.nama_proses}/><Info l="Sections" v={ctx.sections.map(s=>s.nama).join(', ')}/><Info l="Tanggal Pelaksanaan" v={ctx.row.tanggal_pelaksanaan_audit}/></div></Card>
 <Card className="p-5 border-l-4 border-amber-400"><h2 className="font-semibold">2. Sumber Checklist — Read-only</h2><p className="text-xs text-gray-500 mb-3">Catatan kerja sumber bukan Problem formal dan tidak disalin otomatis ke PLOR.</p><div className="grid md:grid-cols-3 gap-2">{Object.entries(ctx.source_details).filter(([,v])=>typeof v!=='object').map(([k,v])=><Info key={k} l={k.replace(/_/g,' ')} v={v as string|number|null}/>)}</div><div className="mt-4 p-3 bg-amber-50"><div className="text-xs font-bold uppercase">Catatan Sumber Checklist</div><div className="whitespace-pre-wrap">{ctx.source_note||'-'}</div></div></Card>
 <Card className="p-5"><h2 className="font-semibold mb-3">3. Auditor / Area</h2><div className="grid md:grid-cols-4 gap-3"><Field label="Auditor Penemu"><Select value={form.auditor_penemu_id??''} onChange={e=>set('auditor_penemu_id',e.target.value||null)}><option value="">— Pilih —</option>{auditors.map(a=><option key={a.id} value={a.id}>{a.nama}</option>)}</Select></Field><Field label="Auditee Area"><Input value={form.auditee_area??''} onChange={e=>set('auditee_area',e.target.value||null)}/></Field><Field label="Tanggal Temuan"><Input type="date" value={form.tanggal_temuan} onChange={e=>set('tanggal_temuan',e.target.value)}/></Field><Field label="Klasifikasi DIS"><Select value={form.klasifikasi_dis??''} onChange={e=>set('klasifikasi_dis',(e.target.value||null) as Finding['klasifikasi_dis'])}><option value="">— Opsional —</option>{Object.values(KLASIFIKASI_DIS).map(v=><option key={v}>{v}</option>)}</Select></Field></div></Card>
 <Card className="p-5"><h2 className="font-semibold mb-3">4. PLOR Formal</h2><div className="grid md:grid-cols-2 gap-3"><Field label="Problem"><Textarea value={form.problem??''} onChange={e=>set('problem',e.target.value||null)}/></Field><Field label="Location"><Textarea value={form.location??''} onChange={e=>set('location',e.target.value||null)}/></Field><Field label="Objective Evidence"><Textarea value={form.objective_evidence??''} onChange={e=>set('objective_evidence',e.target.value||null)}/></Field><Field label="Reference"><Textarea value={form.reference??''} onChange={e=>set('reference',e.target.value||null)}/></Field></div></Card>
 <Card className="p-5"><h2 className="font-semibold mb-3">5. Reference / Clause Suggestions</h2>{ctx.source_reference&&<div className="mb-2">Saran Referensi dari Checklist: <Badge variant="gray">{ctx.source_reference}</Badge> <Button size="sm" variant="secondary" onClick={()=>set('reference',ctx.source_reference)}>Gunakan</Button></div>}{suggestions.map(s=><span key={s.id} className="mr-2">Saran Klausul: <Badge variant="blue">{s.klausul}</Badge> <Button size="sm" variant="secondary" onClick={()=>set('reference',s.klausul)}>Gunakan</Button></span>)}</Card>
 {form.kategori==='C'&&<Card className="p-5"><Field label="6. Saran Perbaikan"><Textarea value={form.saran_perbaikan??''} onChange={e=>set('saran_perbaikan',e.target.value||null)}/></Field></Card>}<Card className="p-5"><h2 className="font-semibold">7. Narrative Preview</h2><Badge variant={isFindingPLORComplete(form)?'green':'amber'}>{isFindingPLORComplete(form)?'Lengkap':'Belum Lengkap'}</Badge><p className="mt-3 whitespace-pre-wrap">{formatFindingNarrative(form)}</p></Card><div className="flex justify-end"><Button disabled={saving} onClick={save}>{saving?'Menyimpan...':'Simpan PLOR'}</Button></div></div></div>}
function Info({l,v}:{l:string;v:string|number|null|undefined}){return <div><div className="text-xs uppercase text-gray-500">{l}</div><div className="font-medium">{v??'-'}</div></div>}
