-- Superseding workflow: reusable Team Audit masters and QA-row checklist execution.
-- Legacy schedule/scope/team data is retained, but no longer generated by instruction edits.

CREATE TABLE public.audit_team_masters (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kode_tim text NOT NULL UNIQUE,
  nama_tim text NOT NULL,
  status text NOT NULL DEFAULT 'Aktif' CHECK (status IN ('Aktif', 'Nonaktif')),
  catatan text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.audit_team_master_members (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  team_id uuid NOT NULL REFERENCES public.audit_team_masters(id) ON DELETE CASCADE,
  auditor_id uuid NOT NULL REFERENCES public.auditors(id) ON DELETE RESTRICT,
  peran text NOT NULL CHECK (peran IN ('Lead', 'Member')),
  urutan_tampil integer NOT NULL DEFAULT 0,
  UNIQUE (team_id, auditor_id)
);

CREATE UNIQUE INDEX uq_audit_team_master_one_lead
  ON public.audit_team_master_members(team_id) WHERE peran = 'Lead';
CREATE INDEX idx_audit_team_master_members_team_id ON public.audit_team_master_members(team_id);
CREATE INDEX idx_audit_team_master_members_auditor_id ON public.audit_team_master_members(auditor_id);

ALTER TABLE public.audit_instruction_rows
  ADD COLUMN team_master_id uuid REFERENCES public.audit_team_masters(id) ON DELETE SET NULL,
  ADD COLUMN catatan_justifikasi_tim text;
CREATE INDEX idx_audit_instruction_rows_team_master_id ON public.audit_instruction_rows(team_master_id);

CREATE FUNCTION public.validate_active_audit_team_lead() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
DECLARE v_team_id uuid;
BEGIN
  IF TG_TABLE_NAME = 'audit_team_masters' THEN
    IF TG_OP = 'DELETE' THEN v_team_id := OLD.id; ELSE v_team_id := NEW.id; END IF;
  ELSE
    IF TG_OP = 'DELETE' THEN v_team_id := OLD.team_id; ELSE v_team_id := NEW.team_id; END IF;
  END IF;
  IF EXISTS (SELECT 1 FROM public.audit_team_masters WHERE id=v_team_id AND status='Aktif')
    AND (SELECT count(*) FROM public.audit_team_master_members WHERE team_id=v_team_id AND peran='Lead') <> 1 THEN
    RAISE EXCEPTION 'Tim Audit aktif harus memiliki tepat satu Lead';
  END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;
CREATE CONSTRAINT TRIGGER trg_validate_active_team_header AFTER INSERT OR UPDATE ON public.audit_team_masters
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_active_audit_team_lead();
CREATE CONSTRAINT TRIGGER trg_validate_active_team_members AFTER INSERT OR UPDATE OR DELETE ON public.audit_team_master_members
  DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION public.validate_active_audit_team_lead();

CREATE TRIGGER set_audit_team_masters_updated_at BEFORE UPDATE ON public.audit_team_masters
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

DROP TRIGGER IF EXISTS trg_sync_instruction_row_scope_team ON public.audit_instruction_rows;

CREATE OR REPLACE FUNCTION public.save_audit_team_master(
  p_id uuid, p_kode_tim text, p_nama_tim text, p_status text, p_catatan text, p_members jsonb
) RETURNS uuid LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
DECLARE v_id uuid; v_leads integer; v_count integer;
BEGIN
  IF nullif(btrim(p_kode_tim), '') IS NULL OR nullif(btrim(p_nama_tim), '') IS NULL THEN
    RAISE EXCEPTION 'Kode dan nama Tim Audit wajib diisi';
  END IF;
  IF p_status NOT IN ('Aktif', 'Nonaktif') OR jsonb_typeof(p_members) <> 'array' THEN
    RAISE EXCEPTION 'Data Tim Audit tidak valid';
  END IF;
  SELECT count(*), count(*) FILTER (WHERE x->>'peran' = 'Lead') INTO v_count, v_leads
    FROM jsonb_array_elements(p_members) x;
  IF v_count <> (SELECT count(DISTINCT x->>'auditor_id') FROM jsonb_array_elements(p_members) x) THEN
    RAISE EXCEPTION 'Auditor dalam satu Tim Audit tidak boleh duplikat';
  END IF;
  IF p_status = 'Aktif' AND v_leads <> 1 THEN RAISE EXCEPTION 'Tim Audit aktif harus memiliki tepat satu Lead'; END IF;
  IF EXISTS (SELECT 1 FROM jsonb_array_elements(p_members) x WHERE x->>'peran' NOT IN ('Lead','Member')) THEN
    RAISE EXCEPTION 'Peran anggota Tim Audit tidak valid';
  END IF;
  IF EXISTS (SELECT 1 FROM jsonb_array_elements(p_members) x LEFT JOIN public.auditors a ON a.id=(x->>'auditor_id')::uuid WHERE a.id IS NULL) THEN
    RAISE EXCEPTION 'Auditor anggota Tim Audit tidak ditemukan';
  END IF;
  IF p_id IS NULL THEN
    INSERT INTO public.audit_team_masters(kode_tim,nama_tim,status,catatan)
      VALUES(btrim(p_kode_tim),btrim(p_nama_tim),p_status,nullif(btrim(p_catatan),'')) RETURNING id INTO v_id;
  ELSE
    UPDATE public.audit_team_masters SET kode_tim=btrim(p_kode_tim),nama_tim=btrim(p_nama_tim),status=p_status,
      catatan=nullif(btrim(p_catatan),'') WHERE id=p_id RETURNING id INTO v_id;
    IF v_id IS NULL THEN RAISE EXCEPTION 'Tim Audit tidak ditemukan'; END IF;
    DELETE FROM public.audit_team_master_members WHERE team_id=v_id;
  END IF;
  INSERT INTO public.audit_team_master_members(team_id,auditor_id,peran,urutan_tampil)
    SELECT v_id,(x->>'auditor_id')::uuid,x->>'peran',COALESCE((x->>'urutan_tampil')::integer,0)
    FROM jsonb_array_elements(p_members) x;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.assign_team_to_instruction_row(p_row_id uuid, p_team_id uuid, p_justification text)
RETURNS void LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
DECLARE v_team public.audit_team_masters%ROWTYPE; v_leads integer; v_snapshot jsonb;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('assign-audit-team'), hashtext(p_row_id::text));
  IF EXISTS (SELECT 1 FROM public.checklists WHERE row_id=p_row_id)
    OR EXISTS (SELECT 1 FROM public.checklist_produk WHERE row_id=p_row_id)
    OR EXISTS (SELECT 1 FROM public.checklist_manufaktur_shift WHERE row_id=p_row_id) THEN
    RAISE EXCEPTION 'Tim audit tidak dapat diubah karena checklist untuk No. Audit ini sudah dibuat. Hapus checklist Draft terlebih dahulu jika tim harus diganti.';
  END IF;
  IF p_team_id IS NULL THEN
    UPDATE public.audit_instruction_rows SET team_master_id=NULL,team=NULL,auditor='[]'::jsonb,
      catatan_justifikasi_tim=NULL WHERE id=p_row_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Baris Instruksi Audit tidak ditemukan'; END IF;
    RETURN;
  END IF;
  SELECT * INTO v_team FROM public.audit_team_masters WHERE id=p_team_id AND status='Aktif';
  IF NOT FOUND THEN RAISE EXCEPTION 'Tim Audit aktif tidak ditemukan'; END IF;
  SELECT count(*) FILTER (WHERE peran='Lead'),
    COALESCE(jsonb_agg(jsonb_build_object('auditor_id',auditor_id,'is_lead',peran='Lead') ORDER BY urutan_tampil,id),'[]')
    INTO v_leads,v_snapshot FROM public.audit_team_master_members WHERE team_id=p_team_id;
  IF v_leads <> 1 THEN RAISE EXCEPTION 'Tim Audit harus memiliki tepat satu Lead'; END IF;
  UPDATE public.audit_instruction_rows SET team_master_id=v_team.id,team=v_team.nama_tim,auditor=v_snapshot,
    catatan_justifikasi_tim=nullif(btrim(p_justification),'') WHERE id=p_row_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Baris Instruksi Audit tidak ditemukan'; END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.require_instruction_team_for_checklist() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.audit_instruction_rows r WHERE r.id=NEW.row_id
    AND r.team_master_id IS NOT NULL AND jsonb_array_length(r.auditor) > 0) THEN
    RAISE EXCEPTION 'Pilih Tim Audit pada Instruksi Internal Audit sebelum membuat checklist.';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_require_team_system_checklist BEFORE INSERT ON public.checklists
  FOR EACH ROW EXECUTE FUNCTION public.require_instruction_team_for_checklist();
CREATE TRIGGER trg_require_team_product_checklist BEFORE INSERT ON public.checklist_produk
  FOR EACH ROW EXECUTE FUNCTION public.require_instruction_team_for_checklist();
CREATE TRIGGER trg_require_team_manufacturing_checklist BEFORE INSERT ON public.checklist_manufaktur_shift
  FOR EACH ROW EXECUTE FUNCTION public.require_instruction_team_for_checklist();

CREATE OR REPLACE FUNCTION public.protect_instruction_team_after_checklist() RETURNS trigger
LANGUAGE plpgsql SET search_path = pg_catalog, public AS $$
BEGIN
  IF (NEW.team_master_id,NEW.team,NEW.auditor,NEW.catatan_justifikasi_tim)
      IS DISTINCT FROM (OLD.team_master_id,OLD.team,OLD.auditor,OLD.catatan_justifikasi_tim)
    AND (EXISTS (SELECT 1 FROM public.checklists WHERE row_id=OLD.id)
      OR EXISTS (SELECT 1 FROM public.checklist_produk WHERE row_id=OLD.id)
      OR EXISTS (SELECT 1 FROM public.checklist_manufaktur_shift WHERE row_id=OLD.id)) THEN
    RAISE EXCEPTION 'Tim audit tidak dapat diubah karena checklist untuk No. Audit ini sudah dibuat. Hapus checklist Draft terlebih dahulu jika tim harus diganti.';
  END IF;
  RETURN NEW;
END;
$$;
CREATE TRIGGER trg_protect_instruction_team_after_checklist BEFORE UPDATE ON public.audit_instruction_rows
  FOR EACH ROW EXECUTE FUNCTION public.protect_instruction_team_after_checklist();

CREATE OR REPLACE FUNCTION public.generate_instruction_from_program(p_program_id uuid, p_tahun integer)
RETURNS TABLE(instruction_id uuid, rows_created integer)
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog, public AS $$
DECLARE v_instruction uuid; v_plan uuid; v_tujuan text; v_count integer := 0; rec record; v_code text; v_marks jsonb;
BEGIN
  PERFORM pg_advisory_xact_lock(hashtext('generate-instruction'), hashtext(p_program_id::text));
  SELECT plan_id,tujuan INTO v_plan,v_tujuan FROM public.audit_programs WHERE id=p_program_id;
  IF v_plan IS NULL THEN RAISE EXCEPTION 'Program atau rencana sumber tidak ditemukan'; END IF;
  IF EXISTS (SELECT 1 FROM public.audit_instructions WHERE program_id=p_program_id) THEN RAISE EXCEPTION 'Instruksi untuk program ini sudah pernah dibuat'; END IF;
  INSERT INTO public.audit_instructions(program_id,tahun_fiskal,tujuan_audit) VALUES(p_program_id,p_tahun,v_tujuan) RETURNING id INTO v_instruction;
  FOR rec IN SELECT app.id,app.proses_master_id,
      (SELECT min(aps.bulan) FROM public.audit_plan_schedule aps WHERE aps.process_id=app.id AND aps.plan) first_month
    FROM public.audit_plan_process app WHERE app.plan_id=v_plan ORDER BY app.urutan_tampil,app.created_at LOOP
    v_code := public.next_qa_audit_code();
    SELECT COALESCE(jsonb_agg(jsonb_build_object('seksi_id',l.seksi_id,'tipe',CASE WHEN l.peran='utama' THEN 'target' ELSE 'terkait' END)) FILTER (WHERE l.peran IS NOT NULL),'[]')
      INTO v_marks FROM public.audit_plan_seksi_link l WHERE l.process_id=rec.id;
    INSERT INTO public.audit_instruction_rows(instruction_id,kode_audit,team_master_id,team,proses_id,pemilik_proses,seksi_marks,auditor,tanggal_plan_audit,urutan_tampil)
      SELECT v_instruction,v_code,NULL,NULL,rec.proses_master_id,s.kepala_seksi,v_marks,'[]'::jsonb,
        CASE WHEN rec.first_month IS NULL THEN NULL ELSE make_date(p_tahun,rec.first_month,15) END,v_count+1
      FROM (SELECT 1) d LEFT JOIN public.seksi s ON s.id=(SELECT (m->>'seksi_id')::uuid FROM jsonb_array_elements(v_marks) m WHERE m->>'tipe'='target' LIMIT 1);
    v_count := v_count+1;
  END LOOP;
  RETURN QUERY SELECT v_instruction,v_count;
END;
$$;

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['audit_team_masters','audit_team_master_members'] LOOP
  EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t);
  EXECUTE format('CREATE POLICY anon_select_%s ON public.%I FOR SELECT TO anon, authenticated USING (true)',t,t);
  EXECUTE format('CREATE POLICY anon_insert_%s ON public.%I FOR INSERT TO anon, authenticated WITH CHECK (true)',t,t);
  EXECUTE format('CREATE POLICY anon_update_%s ON public.%I FOR UPDATE TO anon, authenticated USING (true) WITH CHECK (true)',t,t);
  EXECUTE format('CREATE POLICY anon_delete_%s ON public.%I FOR DELETE TO anon, authenticated USING (true)',t,t);
END LOOP; END $$;
GRANT EXECUTE ON FUNCTION public.save_audit_team_master(uuid,text,text,text,text,jsonb) TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.assign_team_to_instruction_row(uuid,uuid,text) TO anon, authenticated;
