import { useEffect,useState } from 'react';
import { ExternalLink,Plus,Save,Trash2,Upload } from 'lucide-react';
import { LTP_ACTION_TYPE,LTP_ACTION_TYPE_LABEL,LTP_EVIDENCE_STATE,LTP_EVIDENCE_STATE_LABEL,LTP_SYSTEM_REVISION_CATEGORY,type LtpActionType,type LtpEvidenceState,type LtpSystemRevisionCategory } from '../../../lib/enums';
import type { LtpAction,LtpContext,LtpSystemRevision,LtpWhyAnalysis } from '../../../lib/types';
import { deleteLtpActionEvidence,getLtpEvidenceSignedUrl,saveLtpAuditeeDraft,uploadLtpActionEvidence } from '../../../services/ltpService';
import { Button,Card } from '../../ui';
import { Field,Input,Select,Textarea } from '../../ui/Field';

const actionTypes=Object.values(LTP_ACTION_TYPE);
const revisionCategories=Object.values(LTP_SYSTEM_REVISION_CATEGORY);
const DIRTY_EVIDENCE_MESSAGE='Simpan Draft terlebih dahulu sebelum mengubah bukti agar perubahan form tidak hilang.';

export function LtpAuditeeForm({context,onRefresh}:{context:LtpContext;onRefresh:()=>Promise<void>}){
  const editable=context.permissions.can_edit_auditee;
  const [dampak,setDampak]=useState(''),[manfaat,setManfaat]=useState('');
  const [why,setWhy]=useState<LtpWhyAnalysis[]>([]),[actions,setActions]=useState<LtpAction[]>([]),[revisions,setRevisions]=useState<LtpSystemRevision[]>([]);
  const [busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState<string|null>(null),[error,setError]=useState<string|null>(null);
  const formDisabled=!editable||busy;
  useEffect(()=>{
    setDampak(context.ltp.dampak_temuan??'');setManfaat(context.ltp.manfaat_perbaikan??'');
    setWhy(context.finding.kategori==='C'?[]:Array.from({length:Math.max(3,context.why_analysis.length)},(_,i)=>context.why_analysis[i]??{level:i+1,teks:''}));
    setActions(actionTypes.map(action_type=>context.actions.find(a=>a.action_type===action_type)??{action_type,description:editable&&action_type===LTP_ACTION_TYPE.CORRECTIVE&&context.finding.kategori==='C'?(context.finding.saran_perbaikan??''):'',pic:null,due_date:null,evidence:[]}));
    setRevisions(context.system_revisions);setDirty(false);setMessage(null);setError(null);
  },[context,editable]);
  const changeAction=(type:LtpActionType,patch:Partial<LtpAction>)=>{setActions(rows=>rows.map(row=>row.action_type===type?{...row,...patch}:row));setDirty(true);};
  const save=async()=>{setBusy(true);setError(null);setMessage(null);try{await saveLtpAuditeeDraft({car_id:context.ltp.id,expected_revision:context.ltp.revision_version,dampak_temuan:dampak,manfaat_perbaikan:manfaat,why_analysis:why,actions,system_revisions:revisions});await onRefresh();setMessage('Draft LTP berhasil disimpan.');}catch(e){setError(e instanceof Error?e.message:'Gagal menyimpan Draft LTP');}finally{setBusy(false);}};
  const upload=async(action:LtpAction,state:LtpEvidenceState,files:File[])=>{if(!files.length)return;if(dirty){setError(DIRTY_EVIDENCE_MESSAGE);return;}if(!action.id){setError('Simpan Draft terlebih dahulu untuk mengaktifkan upload bukti.');return;}setBusy(true);setError(null);try{for(const file of files)await uploadLtpActionEvidence(context.ltp.id,action.id,state,file);await onRefresh();}catch(e){setError(e instanceof Error?e.message:'Gagal mengunggah bukti');}finally{setBusy(false);}};
  const removeEvidence=async(evidence:LtpAction['evidence'][number])=>{if(dirty){setError(DIRTY_EVIDENCE_MESSAGE);return;}setBusy(true);setError(null);try{await deleteLtpActionEvidence(evidence);await onRefresh();}catch(e){setError(e instanceof Error?e.message:'Gagal menghapus bukti');}finally{setBusy(false);}};
  const openEvidence=async(path:string)=>{try{window.open(await getLtpEvidenceSignedUrl(path),'_blank','noopener,noreferrer');}catch(e){setError(e instanceof Error?e.message:'Gagal membuka bukti');}};
  return <>
    {(error||message)&&<div className={`p-3 rounded-lg text-sm ${error?'bg-red-50 text-red-700':'bg-green-50 text-green-700'}`}>{error??message}</div>}
    <Card className="p-5"><h2 className="font-semibold mb-4">3. Respon Auditee</h2><div className="grid md:grid-cols-2 gap-4"><Field label="Dampak Temuan"><Textarea rows={4} value={dampak} disabled={formDisabled} onChange={e=>{setDampak(e.target.value);setDirty(true);}}/></Field><Field label="Manfaat Perbaikan"><Textarea rows={4} value={manfaat} disabled={formDisabled} onChange={e=>{setManfaat(e.target.value);setDirty(true);}}/></Field></div></Card>
    <Card className="p-5"><h2 className="font-semibold mb-4">4. Analisa Why-Why</h2>{context.finding.kategori==='C'?<p className="text-sm text-gray-600">Kategori C tidak memerlukan analisa Why-Why.</p>:<div className="space-y-3">{why.map((row,index)=><Field key={index} label={`Why ${index+1}`}><div className="flex gap-2"><Textarea rows={2} value={row.teks} disabled={formDisabled} onChange={e=>{setWhy(items=>items.map((item,i)=>i===index?{...item,teks:e.target.value}:item));setDirty(true);}}/>{editable&&why.length>3&&<Button variant="ghost" disabled={busy} onClick={()=>{setWhy(items=>items.filter((_,i)=>i!==index).map((item,i)=>({...item,level:i+1})));setDirty(true);}}><Trash2 size={15}/></Button>}</div></Field>)}{editable&&<Button variant="secondary" disabled={busy} onClick={()=>{setWhy(items=>[...items,{level:items.length+1,teks:''}]);setDirty(true);}}><Plus size={15}/> Tambah Why</Button>}</div>}</Card>
    <Card className="p-5"><h2 className="font-semibold mb-4">5. Tindakan Perbaikan</h2><div className="space-y-5">{actions.map(action=><div key={action.action_type} className="border rounded-lg p-4"><h3 className="font-medium mb-3">{LTP_ACTION_TYPE_LABEL[action.action_type]}</h3><div className="grid md:grid-cols-2 gap-3"><Field label="Deskripsi" className="md:col-span-2"><Textarea rows={3} value={action.description} disabled={formDisabled} onChange={e=>changeAction(action.action_type,{description:e.target.value})}/></Field><Field label="PIC"><Input value={action.pic??''} disabled={formDisabled} onChange={e=>changeAction(action.action_type,{pic:e.target.value||null})}/></Field><Field label="Due Date"><Input type="date" value={action.due_date??''} disabled={formDisabled} onChange={e=>changeAction(action.action_type,{due_date:e.target.value||null})}/></Field></div><div className="grid md:grid-cols-2 gap-3 mt-4">{Object.values(LTP_EVIDENCE_STATE).map(state=><Evidence key={state} className={state===LTP_EVIDENCE_STATE.BEFORE_AFTER?'md:col-span-2':undefined} label={LTP_EVIDENCE_STATE_LABEL[state]} uploadLabel={state===LTP_EVIDENCE_STATE.BEFORE_AFTER?'Upload Perbandingan':'Upload Bukti'} state={state} action={action} editable={editable} busy={busy} dirty={dirty} onUpload={upload} onOpen={openEvidence} onDelete={removeEvidence}/>)}</div></div>)}</div></Card>
    <Card className="p-5"><h2 className="font-semibold mb-4">6. Revisi Sistem</h2><div className="space-y-3">{revisions.map((row,index)=><div key={index} className="grid md:grid-cols-[220px_1fr_auto] gap-2"><Select value={row.kategori} disabled={formDisabled} onChange={e=>{setRevisions(items=>items.map((item,i)=>i===index?{...item,kategori:e.target.value as LtpSystemRevisionCategory}:item));setDirty(true);}}>{revisionCategories.map(value=><option key={value}>{value}</option>)}</Select><Input placeholder="Nama dokumen" value={row.nama_dokumen} disabled={formDisabled} onChange={e=>{setRevisions(items=>items.map((item,i)=>i===index?{...item,nama_dokumen:e.target.value}:item));setDirty(true);}}/>{editable&&<Button variant="ghost" disabled={busy} onClick={()=>{setRevisions(items=>items.filter((_,i)=>i!==index));setDirty(true);}}><Trash2 size={15}/></Button>}</div>)}{editable&&<Button variant="secondary" disabled={busy} onClick={()=>{setRevisions(items=>[...items,{kategori:LTP_SYSTEM_REVISION_CATEGORY.ISE,nama_dokumen:''}]);setDirty(true);}}><Plus size={15}/> Tambah Dokumen</Button>}</div></Card>
    <Card className="p-5 border-l-4 border-blue-400"><p className="text-sm text-gray-600 mb-4">Submit ke Section Manager akan diaktifkan pada tahap review berikutnya.</p>{editable&&<Button disabled={busy} onClick={()=>void save()}><Save size={16}/> {busy?'Menyimpan...':'Simpan Draft'}</Button>}</Card>
  </>;
}

function Evidence({className,label,uploadLabel,state,action,editable,busy,dirty,onUpload,onOpen,onDelete}:{className?:string;label:string;uploadLabel:string;state:LtpEvidenceState;action:LtpAction;editable:boolean;busy:boolean;dirty:boolean;onUpload:(a:LtpAction,s:LtpEvidenceState,f:File[])=>void;onOpen:(p:string)=>void;onDelete:(e:LtpAction['evidence'][number])=>void}){
  const files=action.evidence.filter(file=>file.evidence_state===state);
  const mutationDisabled=busy||dirty;
  return <div className={`bg-gray-50 rounded-lg p-3 ${className??''}`}><div className="flex justify-between items-center mb-2"><span className="text-sm font-medium">{label}</span>{editable&&action.id&&<label className={`text-xs inline-flex gap-1 ${mutationDisabled?'text-gray-400 cursor-not-allowed':'text-blue-600 cursor-pointer'}`}><Upload size={13}/> {uploadLabel}<input type="file" multiple className="hidden" disabled={mutationDisabled} onChange={e=>{const selected=Array.from(e.target.files??[]);e.target.value='';void onUpload(action,state,selected);}}/></label>}</div>{editable&&!action.id&&<p className="text-xs text-amber-700">Simpan Draft terlebih dahulu untuk mengaktifkan upload bukti.</p>}{editable&&action.id&&dirty&&<p className="text-xs text-amber-700 mb-2">{DIRTY_EVIDENCE_MESSAGE}</p>}<div className="space-y-1">{files.map(file=><div key={file.id} className="flex justify-between gap-2 text-xs bg-white p-2 rounded"><span className="truncate">{file.file_name}</span><span className="flex gap-2"><button className="text-blue-600" onClick={()=>onOpen(file.path)}><ExternalLink size={13}/></button>{editable&&<button disabled={mutationDisabled} className="text-red-600 disabled:text-gray-400 disabled:cursor-not-allowed" onClick={()=>onDelete(file)}><Trash2 size={13}/></button>}</span></div>)}</div></div>;
}
